### ISSUE TITLE
The assertion mechanism is unsound

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#10]
Our assertion mechanism is pretty lightweight and has served us well, but there are places where optimisations break it, and there is really no way for the optimiser to be more careful.  Look at this program:

```
fun int main([int] a, int m) =
  let n = size(0,a) in
  loop (x=0) = for i < n do
    x+a[0]
  in
  x
```

After internalisation it looks like this:

```
fun [int] main(int a_size_0, [int,a_size_0] a_1, int m_2) =
  let {int n_3} = a_size_0 in
  let {int val_18} = 0 in
  let {int x_27} =
    loop {int x_19} <- {int x_19} = {val_18}
    for i_20 < n_3 do
      let {bool x_21} = 0 <= 0 in
      let {bool y_22} = 0 < a_size_0 in
      let {bool assert_arg_23} = x_21 && y_22 in
      let {cert bounds_check_24} = assert(assert_arg_23) in
      let {int y_25} = <bounds_check_24>a_1[0] in
      let {int res_26} = x_19 + y_25 in
      {res_26} in
  {x_27}
```

While the assertion is technically loop-invariant, the compiler is smart enough not to hoist assertions out of loops and branches.  However, the loop is only entered if `0 < n`, in which case the bounds check will always succeed.  The optimiser will realise this and remove the assertion, but now the array index is loop-invariant, and the optimiser has no idea that it is only valid due to the invariants provided by entering the loop.  Hence, it will be hoisted, and the result will be the following unsafe (but fast!) program.

```
fun [int] main(int a_size_3, [int,a_size_3] a_4, int m_5) =
  let {int y_6} = a_4[0] in
  let {int x_10} =
    loop {int x_7} <- {int x_7} = {0}
    for i_8 < a_size_3 do
      let {int res_9} = x_7 + y_6 in
      {res_9} in
  {x_10}
```

One way to solve this would be to be much more conservative about when we hoist - for example, never hoist anything that can accept certification certificates, but this is very problematic because that is most expressions due to the assert-zip mechanism.

The assert-zip mechanism itself is alright.  It means that this program

```
fun [{int,int}] main([int] a, [int] b) =
  zip(a,b)
```

becomes this

```
fun {cert, [int,?0], [int,?1]} main(int a_size_0, int b_size_1,
                                    [int,a_size_0] a_8, [int,b_size_1] b_9) =
  let {bool zip_cmp_10} = a_size_0 == b_size_1 in
  let {cert zip_assert_11} = assert(zip_cmp_10) in
  {zip_assert_11, a_8, b_9}
```

However, this has forced us to add certificate-dependency slots to all sorts of expressions in order to ensure that the assertions are not optimised away.  It also means we have pseudo-hacks like functions returning certificates (as above), functions accepting certificates as arguments, and, worst of all, a certificate slot in _body results_.  This last one is a major problem, because there are several optimisations, notably fusion, that do not preserve them.  For example, this program

```
fun [int] main([[int]] a, [[int]] b) =
  let c = map(fn [{int,int}] ([int] ar, [int] br) =>
                zip(ar, br),
              zip(a,b)) in
  map(fn int ([{int,int}] p) =>
        let {p1, p2} = unzip(p) in
        reduce(op+, 0, p1) + reduce(op+, 0, p2),
      c)
```

we would expect to fail if the inner sizes of `a` and `b` do not match, but after optimisation, we note that only the assertion for the outer sizes has been preserved:

```
fun {[int,?0]} main(int a_size_8, int a_size_9, int b_size_10, int b_size_11,
                    [[int,a_size_9],a_size_8] a_12,
                    [[int,b_size_11],b_size_10] b_13) =
  let {bool zip_cmp_17} = a_size_8 == b_size_10 in
  let {cert zip_assert_18} = assert(zip_cmp_17) in
  let {bool cond_14} = a_size_8 == 0 in
  let {int shape_15, int shape_16} =
    if cond_14
    then {0, 0}
    else {a_size_9, b_size_11} in
  let {[int,a_size_8] res_30} =
    <zip_assert_18>
    mapT(fn {int} ([int,shape_15] p_19, [int,shape_16] p_20) =>
           let {int x_28} =
             reduceT(fn {int} (int x_25, int y_26) =>
                       let {int res_27} = x_25 + y_26 in
                       {res_27},
                     {0}, p_19) in
           let {int y_24} =
             reduceT(fn {int} (int x_21, int y_22) =>
                       let {int res_23} = x_21 + y_22 in
                       {res_23},
                     {0}, p_20) in
           let {int res_29} = x_28 + y_24 in
           {res_29},
         a_12, b_13) in
  {res_30}
```

(In this case, I think the problem is in the simplification rule that recognises identity maps, but fusion would mess this up as well.)

Now that we have sizes in our type system, we could replace this part of the assertion system with a typecasting mechanism instead.  For example, we could compile the first zip-example to this instead:

```
fun {[int,?0], [int,?0]} main(int a_size_0, int b_size_1,
                                    [int,a_size_0] a_8, [int,b_size_1] b_9) =
  let {bool zip_cmp_10} = a_size_0 == b_size_1 in
  let {cert zip_assert_11} = assert(zip_cmp_10) in
  let {[int,a_size_0] c_12} = <zip_assert_11>typecast([int,a_size_0], b_9)
  {a_8, b_9}
```

The assertion functions as a witness that the type of `b_9` is identical to the one of `a_8`.  This is still a fairly lightweight mechanism, but I think it is much less vulnerable to mangling.

**Comment by Athas** [comment]
Hm, isn't the hypothetical `typecast` really just `reshape`?

**Comment by melsman** [comment]
Don't you just need also to hoist the condition under which the hoisted
code executes?

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> Don't you just need also to hoist the condition under which the hoisted
> code executes?

Possibly, but I'm uncertain about the consequences of adding a lot more
branches in the hoisted code.  For instance, in the "false" branch of
those new expressions, we will have to construct some dummy value of the
proper type.  What if this type involves some shape that can itself only
be computed under the branch?  Then the shape of the type suddenly
becomes existential, even though it was non-existential inside the
original loop.  And maybe the loop criterion doesn't even matter for the
safety of the expression to begin with!

I agree that it's the simplest solution to implement, however, so I will
probably do that for now.

This still does not solve the other issue, where some optimisations
throw away assertions, but I think I have found another way to fix
that.  In the current implementation, if we want to `map` across two
arrays `a` and `b`, we need to ensure that they have the same outer
size.  This is done with an `assert` expression that produces a value of
type `cert` (for "certificate"), which is then referenced by the `map`
expression.  This creates a data-dependency between the `map` and the
`assert` and ensures that it is not optimised away unless the `assert`
can be determined at compile-time:

````
let [int,n] a = ...
let [int,m] b = ...
let cert c = assert(n==m)
map<c>(..., a, b)
````

When type-checking the `map`, we don't really care what the
shape-annotations in the types of `a` and `b` look like - we assume that
any checking has been done by the assertions that the `map` depends on.
I think a better design is to be much more strict, and require total
equality of the outer sizes of the arguments.  Then, we use `reshape` to
force the arguments into having the same outer size:

````
let [int,n] = a ...
let [int,m] = b ...
let cert c = assert(n==m)
let [int,n] = <c>reshape((n), b')
map(..., a, b')
````

Now `reshape` acts like sort of a type-cast.  In particular, note that
`reshape` is completely free at run-time -- this is how it is
implemented in the code generator:

````
defCompilePrimOp [_] (Reshape {}) =
  return ()
````

By encoding these shape invariants in the types themselves, we should
have a much easier time preserving them in the optimiser.

(Mostly writing this down so I'll remember it myself.)

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
The `better-assertions` branch now has a better design of assertions, using `reshape` as a kind of type-coercion operation.  The following problems have prevented me from merging into `master`:

    * `reshape` is not ideal, as strictly we have stronger invariants (the old and new dimensions are the same).

    * Not all of the `reshape` operations are optimised away, thus providing an obstacle to fusion in some cases.

**Comment by Athas** [comment]
The `better-assertions`-branch has been merged into `master`.  Now the remaining big issue is in hoisting, but that is comparatively much simpler.
