### ISSUE TITLE
Deal with equality checking of arrays

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#110]
Currently, the external language will accept expressions of the form `x == y` where `x` and `y` are of (the same) array type.  However, the corresponding internal language construct will reject this - the equality operator works only on primitives.

I think comparing arrays for equality should be permitted.  During internalisation, we should convert this to a branch checking that the size of the two arrays are the same, followed by a `map`-`reduce` equality comparison.

**Comment by melsman** [comment]
Should it work only on boolean, character, and integer arrays?

On Tue, Jan 26, 2016 at 11:36 PM, Troels Henriksen <notifications@github.com

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> Should it work only on boolean, character, and integer arrays?

No, any two arrays of the same type.

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
... including arrays of type [double] and [float]?

On Wed, Jan 27, 2016 at 10:03 AM, Troels Henriksen <notifications@github.com
> wrote:

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> ... including arrays of type [double] and [float]?

Yes, of course.  These have well-defined equality at the hardware level
(bit pattern equality).  The user is free to write his own map-reduce
comparison code if he wants to, but I am strongly against hiding the
actual nature of the hardware.

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
Giving semantics to a concept is all about hiding the actual nature of the
underlying phenomenon... ;)

On Wed, Jan 27, 2016 at 10:29 AM, Troels Henriksen <notifications@github.com
> wrote:

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> Giving semantics to a concept is all about hiding the actual nature of the
> underlying phenomenon... ;)

Indeed, but Futhark is (at this stage) a fairly low-level language
concerned mostly with performance.  There is little point in an
abstraction that simply obscures the hardware without granting
additional generality or power.

Another argument is that you cannot implement bitwise equality yourself
if the language itself does not have it.  Well, you can if you have a
low-level bitcast operation, and I suppose Futhark will eventually.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
Since the Futhark book is now filled with array comparisons, we should probably make them work.
