### ISSUE TITLE
Simple type alias and record system

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#113]
At the moment, Futhark has no way of defining new types, which means that some benchmark programs are fairly cumbersome to write.  I suggest adding two features as a start.

Type aliases:

```
type point = {f32, f32}
type line = {point, point}
```

These work exactly like type aliases in any other functional language.

Records as syntactical sugar for tuples:

```
record point = { x : f32, y : f32 }
record line = { start : point, end : point }
```

The syntax for accessing a record will be the familiar dot-notation: `line.start.x`.  I also suggest extending this a little bit, such that if `p` is a tuple, `p.*i*` (where _i_ is an integer constant) accesses the _i_th component of the tuple.  This is similar to the projection functions in SML, but with a more familiar syntax.

The advantage of this scheme is its simplicity: it requires no change to the core language.  Another is that it can easily be extended to support simple type application eventually:

```
type pixel = { r : u8, g : u8, b : u8 }
type image n m = [[pixel,m],n]
```

(Although in this case, `n` and `m` are actually not types, but terms.)

**Comment by Athas** [comment]
It is time to add records.  The notation will be taken mostly from SML.  A *record type* is enclosed in curly braces, and contains `field: type` pairs, separated by commas:

```
type rt = {x: i32, y: i32, z: bool}
```

A *record expression* is a comma-separated sequence of `field = value` pairs enclosed in curly braces:

```
let rt: rv = {x=2, y=1, z=false}
```

Field values are extracted with `#k`, where *k* is the name of the field:

```
#y rv == 1 
```

This is exactly like SML so far.  Unlike SML, I don't intend to add record patterns yet, or partial records, or any of the other advanced features.

The only place where I intend to diverge from SML is that I want to support *record updates*, where we copy a record while replacing the values of some of the fields.  Successor-ML did have a proposed notation which was something like this:

```
x with { x = 42, c = true }
```

This is fine, but since Futhark expressions tend to use non-alphabetic symbols rather than words, maybe it sticks out a bit too much.  The Elm language uses something like this:

```
{ x | x = 42, c = true }
```

Of course, this looks a little like a set comprehension, so the mathematicians will be upset.  One notation I definitely *do not want* is the one from Haskell:

```
x { x = 42, c = true }
```

This is just too hard to disambiguate in the parser (is it an update of `x` or an application of the function `x` to a record?).

Thoughts?

**Comment by Athas** [comment]
Actually, I guess the Haskell notation is possible if we simply say that a record (`rv`) can be applied to another record `{ x = 42, c = true }` iff the latter record contains a subset of the records in `rv`.

**Comment by Athas** [comment]
OCaml uses the following:

```
{ <record> with <field> = <value>;
                <field> = <value>;
                ...
}
```

Basically what I have above, except with semicolons and `with` instead of `|`.

**Comment by Munksgaard** [comment]
> Actually, I guess the Haskell notation is possible if we simply say that a record (rv) can be applied to another record { x = 42, c = true } iff the latter record contains a subset of the records in rv.

I like the Haskell notation, and I had this thought as well.

It might even be possible to allow supersets in the latter record. For example:

```
{ x = 42, c = true } { c = false }                  =>     { x = 42, c = false }
{ x = 42, c = true } { c = false, v = 3.14 }   =>     { x = 42, c = false, v = 3.14 }
```

The latter application changes the type of the record, but I'm not sure that's a big problem.

IIRC, OCaml has something similar, that allows you to easily add members to a record.

**Comment by Munksgaard** [comment]
Also, your first and second comment uses two different methods for accessing records. Do you intend to support both `x.y` and `#y x`?

**Comment by Athas** [comment]
No, the first comment is old.  I no longer want the dot notation (we use it at the module level instead).  I want `#y x` because it works more like a function.

The problem with permitting `{ x = 42, c = true } { c = false, v = 3.14 }` is that it is very easy to screw up by mistyping a field name, and the compiler won't complain.

**Comment by Munksgaard** [comment]
> The problem with permitting { x = 42, c = true } { c = false, v = 3.14 } is that it is very easy to screw up by mistyping a field name, and the compiler won't complain.

That's a good point. I frequently find myself wanting an "this record struct, but with this additional field" operator in Standard ML, but perhaps a more explicit approach is better. Just having the record update syntax would be great.

**Comment by Athas** [comment]
Another option: `{rv, x = 42, c= true}`.  This looks somewhat natural, especially if we do support adding more fields.

**Comment by melsman** [comment]
OCaml features the following derived form for expressions:

{...,x,...}          ==>         {...,x=x,...}

This nice feature does not work well with the syntax below. How about {r;
x1=e1,...xn=en} for record update?

tir. 28. feb. 2017 kl. 15.03 skrev Troels Henriksen <
notifications@github.com>:

**Comment by Athas** [comment]
Is that syntax particularly useful?  I must admit I've found it confusing.  I like that one could write, say, `{rv1, rv2}` to get a record that is the union of the fields in `rv1` and `rv2`, preferring `rv2` in case of duplicates.

**Comment by Athas** [comment]
We could support something like OCaml another way: `{x=}` understood as `{x=x}`.  But I'm not really sure it's necessary.

**Comment by melsman** [comment]
fun plus {x,y} {x=x',y=y'}=
  let x=x+x'
  let y=y+y'
  in {x,y}

Best,

Martin

tir. 28. feb. 2017 kl. 17.12 skrev Troels Henriksen <
notifications@github.com>:

**Comment by Athas** [comment]
That looks really awkward to me, to be honest.  I especially dislike that two things that are the same (binding the fields of the parameters) look distinct.  I feel like I'm missing some subtlety when I'm reading that definition.  I much prefer:

```
fun plus {x=x1,y=y1} {x=x2,y=y2} =
  {x = x1 + x2,
   y = y1 + y2}
```

**Comment by Athas** [comment]
I'm speculating a little more about treating records as functions.  Then `rv1 rv2` produces a record that is the union of the fields in `rv1` and `rv2`, preferring fields from `rv1` in case of duplicates.  The advantage is that you can do things like `map {x=2} l` to update everything in an array, without writing an explicit lambda.

**Comment by Athas** [comment]
I will implement record types and expression syntax, as this seems non-controversial.  For record updates, I'm leaning towards `{rv, x = 42, c= true}` as the best one, but we can decide later.

**Comment by Athas** [comment]
Tuples will be considered more or less syntactic sugar for records, as in SML.

**Comment by Athas** [comment]
I'll also switch to 1-indexed tuples when doing this.
