### ISSUE TITLE
Multiple entry points

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#117]
Right now Futhark assumes a single entry point: `main`.  It is sometimes convenient to have multiple entry points when the Futhark program is not a standalone program, but rather a module to be called by e.g. Python via `futhark-pyopencl`.

**Comment by nqpz** [comment]
For the record, I just added an `include` header in 6b73e46d804c50e6870547853a36d096f01f3d3c.  Now you can have multiple entry points by creating multiple files that include the same library.

**Comment by Athas** [comment]
Fine with me, for now.  My only objection is that we now have two things we seem to call modules: the files included through this facility, and whatever @MikkelStorgaard is cooking up.  We should figure out how to deal with this.  FWIW, Java calls files "packages", I think.

**Comment by nqpz** [comment]
On 2016-02-28 06:08:56, Troels Henriksen wrote:
> Fine with me, for now.  My only objection is that we now have two things we seem to call modules: the files included through this facility, and whatever @MikkelStorgaard is cooking up.  We should figure out how to deal with this.  FWIW, Java calls files "packages", I think.

By the way, the only reason why I currently name the included files
".fut.module" is to make sure the test script in the repo doesn't
complain when it tries to run a Futhark file with no main function.

But yes, @MikkelStorgaard needs to think about this naming.

**Comment by Athas** [comment]
Added this in a768e9d9ab2249eab4477e88c34608adace85fea.
