### ISSUE TITLE
Remove the `real` type from the language

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#118]
Ever since Futhark was first conceived (before I arrived!), the default floating-point type has been called `real`.  What exactly this type means is left to the compiler, and is in fact toggleable with a command line flag.

This is horrible.  Code should specify its type concretely, or use a proper generic/polymorphic language mechanism (which we do not have yet).  We need to change old code to use either `f32` or `f64` as appropriate, and then we can get rid of `real`.

**Comment by oleks** [comment]
:+1:

**Comment by Athas** [comment]
One problem is that floating-point literals without a suffix are presently considered to be of type `real`, and transparently converted to either `f32` or `f64`.  This can eventually be handled with lightweight type inference, but as a short-term solution, Futhark could permit a program to have a leading declaration stating whether decimal literals with no suffix should be considered `f32` or `f64`.  It could look like:

```
real = f32
```

(At the top level - then we can even re-use the keyword!)

This is very similar to Haskell's little known `default` keyword.

**Comment by oleks** [comment]
On Wed, Feb 24, 2016 at 9:49 PM, Troels Henriksen <notifications@github.com>
wrote:

> One problem is that floating-point literals without a suffix are presently
> considered to be of type real, and transparently converted to either f32
> or f64. This can eventually be handled with lightweight type inference,
> but as a short-term solution, Futhark could permit a program to have a
> leading declaration stating whether decimal literals with no suffix should
> be considered f32 or f64. It could look like:
>
> real = f32
>
> (At the top level - then we can even re-use the keyword!)
>
> This is very similar to Haskell's little known default keyword.
>
If your gut-feeling is that someone (me?) at some point will add other
representations of "reals", then I agree, a `default`-like solution sounds
best. Else, I'd abolish the keyword `real` entirely in favor of a keyword
`float`, if anything.

**Comment by henglein** [comment]
A data type that does not implement correctly (effective) real numbers,
shouldn't be called real. And the semantics of a type shouldn't be
implementation-dependent.  Even C has come around to that conclusion, where
"int", "long", etc., are considered bad/deprecated coding style  since C99.

F

**Comment by oleks** [comment]
On Thu, Feb 25, 2016 at 9:02 AM, Fritz Henglein <notifications@github.com>
wrote:

> A data type that does not implement correctly (effective) real numbers,
> shouldn't be called real. And the semantics of a type shouldn't be
> implementation-dependent. Even C has come around to that conclusion, where
> "int", "long", etc., are considered bad/deprecated coding style since C99.
>

:+1:

**Comment by Athas** [comment]
Fritz Henglein <notifications@github.com> writes:

> A data type that does not implement correctly (effective) real numbers,
> shouldn't be called real. And the semantics of a type shouldn't be
> implementation-dependent.  Even C has come around to that conclusion, where
> "int", "long", etc., are considered bad/deprecated coding style  since C99.

Agreed.  The only question then is whether to use `float` or `decimal`
for the annotation.  Remember - it affects nothing apart from how bare
decimal literals (e.g `12.3`) are interpreted.

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Thu, Feb 25, 2016 at 9:42 AM, Troels Henriksen <notifications@github.com>
wrote:
>
> Agreed. The only question then is whether to use `float` or `decimal`
> for the annotation. Remember - it affects nothing apart from how bare
> decimal literals (e.g `12.3`) are interpreted.


What's wrong with a little type-inference and have it depend on the type of
the final expression, which you have to state anyway?

**Comment by Athas** [comment]
Oleks <notifications@github.com> writes:

> On Thu, Feb 25, 2016 at 9:42 AM, Troels Henriksen <notifications@github.com>
> wrote:
>>
>> Agreed. The only question then is whether to use `float` or `decimal`
>> for the annotation. Remember - it affects nothing apart from how bare
>> decimal literals (e.g `12.3`) are interpreted.
>
>
> What's wrong with a little type-inference and have it depend on the type of
> the final expression, which you have to state anyway?

It takes more effort (an unknown amount) to implement, and we have
little manpower as it is.  I'm not much for a solution I cannot
implement in the time between dinner and bed, or alternatively between
breakfast and lunch.

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
In that case, let's do a [proper `default` construct](https://wiki.haskell.org/Keywords#default):

    default(i32, f64)

Is assumed by default - those do seem to be Futhark defaults ATM. User can then e.g. write:

    default(i64, f32)

To let integer literals be 64-bit ints and let decimal literals be 32-bit floats.

... And purge the `real` keyword. Luckily, that was exactly what I had started on my local branch yesterday when you assigned me the issue :+1:

**Comment by Athas** [comment]
Oleks <notifications@github.com> writes:

> In that case, let's do a [proper `default`
> construct](https://wiki.haskell.org/Keywords#default):
>
>     default(i32, f64)
>
> Is assumed by default - those do seem to be Futhark defaults ATM. User can then e.g. write:
>
>     default(i64, f32)
>
> To let integer literals be 64-bit ints and let decimal literals be 32-bit floats.
>
> ... And purge the `real` keyword. Luckily, that was exactly what I had
> started on my local branch yesterday when you assigned me the issue
> :+1:

Fine by me.  You are implementing this?

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Thu, Feb 25, 2016 at 10:24 AM, Troels Henriksen <notifications@github.com
> wrote:
>
> Fine by me. You are implementing this?


Sure.
