### ISSUE TITLE
Add isnan function

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#119]
We need to be able to determine whether some float is NaN.  I am not sure how this should be implemented - as just a standard function?  Built-in construct?  Via adding a bitcast, letting users write it themselves in Futhark?

**Comment by oleks** [comment]
Then you should add isinf as well, and exception handlers for overflow and underflow, but that sounds too complicated. In general, it would be nice if you could control your [floating-point environment](http://en.cppreference.com/w/c/numeric/fenv).

**Comment by Athas** [comment]
Oleks <notifications@github.com> writes:

> Then you should add isinf as well, and exception handlers for overflow
> and underflow, but that sounds too complicated. In general, it would
> be nice if you could control your [floating-point
> environment](http://en.cppreference.com/w/c/numeric/fenv).

Exception handlers are not a realistic possibility.  `isinf` is easy, is
it not?  Or are there multiple representations of positive and negative
infinity, the way there is for NaN?

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
Oleks <notifications@github.com> writes:

> In general, it would be nice if you could control your [floating-point
> environment](http://en.cppreference.com/w/c/numeric/fenv).

Also, there is no way the GPUs support anything like this.

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Thu, Feb 25, 2016 at 1:18 PM, Troels Henriksen <notifications@github.com>
wrote:

> Oleks <notifications@github.com> writes:
>
> > Then you should add isinf as well, and exception handlers for overflow
> > and underflow, but that sounds too complicated. In general, it would
> > be nice if you could control your [floating-point
> > environment](http://en.cppreference.com/w/c/numeric/fenv).
>
> Exception handlers are not a realistic possibility. `isinf` is easy, is
> it not? Or are there multiple representations of positive and negative
> infinity, the way there is for NaN?


`isinf` is easy yes, sorry for being ambiguous.

Also, controlling which way your floats round is easy both on a CPU (using
fenv.h) and e.g. [on CUDA](
http://docs.nvidia.com/cuda/floating-point/index.html#rounding-modes).

Exception handlers are the hard part and can, i.e. should be put off until
there is a general strategy for run-time exceptions.

**Comment by he-la** [comment]
Resurrecting this to state that it would be nice if the REPL could offer floating point exceptions, e.g. break on nan, since it already supports breakpoints and debugging.

**Comment by athas** [comment]
I guess that wouldn't be difficult to add (feel free to make create an issue if you really want it), but it's also easy to add in ad-hoc places as a function of your own:

```
let nancheck (x: f32) : f32 = if f32.isnan x then break x else x
```

**Comment by he-la** [comment]
This is what I'm doing now, but as far as I can tell the repl doesn't support navigating through the call stack (?) so I am inlining this little snippet everywhere to chase my bugs. It would be nice to automate the process - I have opened a separate issue here: #839.

**Comment by athas** [comment]
Adding call stack navigation sounds pretty doable.  If it would be useful, please make an issue about that, too.
