### ISSUE TITLE
Add a test program solving Guy Steele's "Trivial Problem"

### ISSUE THREAD

**Issue by oleks** [HIPERFIT/futhark#121]
See https://gist.github.com/Teggy/1f525cf3027c92d9008d or https://www.youtube.com/watch?v=ftcIcn8AmSY

**Comment by Athas** [comment]
Nice problem!  Who's up for this one?

**Comment by Athas** [comment]
I think the "sequential" version in the Haskell implementation is the easiest to translate and the most immediately efficient one.  It is certainly not sequential, as it consists of two scans, followed by two maps, followed by a reduce.  The two maps can be fused into the reduction.

**Comment by Athas** [comment]
I added an adaptation of the "sequential" version: https://github.com/HIPERFIT/futhark/blob/master/data/tests/guysteele_sequential.fut

The others are tricky to implement in Futhark, because they require variable-length lists (and I am not convinced they would be much faster anyway).

**Comment by oleks** [comment]
:+1:
