### ISSUE TITLE
Add a `const` construct

### ISSUE THREAD

**Issue by oleks** [HIPERFIT/futhark#123]
I'm thinking [Go-style constants](https://blog.golang.org/constants), implemented initially, as mere nullary functions. So e.g.

    const f64 e = 2.718281828459045235360287471352662497757247093699959574966

Instead of

    fun f64 e() = 2.718281828459045235360287471352662497757247093699959574966

**Comment by Athas** [comment]
Oleks <notifications@github.com> writes:

> I'm thinking [Go-style constants](https://blog.golang.org/constants),
> implemented initially, as mere nullary functions. So e.g.
>
>     const f64 e = 2.718281828459045235360287471352662497757247093699959574966
>
> Instead of
>
>     fun f64 e() = 2.718281828459045235360287471352662497757247093699959574966

Please do this.

-- 
\  Troels
/\ Henriksen
