### ISSUE TITLE
Add a compensated sum primitive to Futhark

### ISSUE THREAD

**Issue by oleks** [HIPERFIT/futhark#124]
Safe(r) floating-point array combinators are all the rage.
Some sources on how to sum a little better:
- https://en.wikipedia.org/wiki/Kahan_summation_algorithm
- http://alex.uwplse.org/2015/10/16/improving-accuracy-summation.html

**Comment by Athas** [comment]
Oleks <notifications@github.com> writes:

> Safe(r) floating-point SOACs are all the rage.

This isn't much of a SOAC now, is it?

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Wed, Mar 2, 2016 at 8:19 PM, Troels Henriksen <notifications@github.com>
wrote:

> Oleks <notifications@github.com> writes:
>
> > Safe(r) floating-point SOACs are all the rage.
>
> This isn't much of a SOAC now, is it?


AC(K)

**Comment by oleks** [comment]
I'll check if this can be done in Futhark without extending the language first.
