### ISSUE TITLE
Patch to complie on OSX

### ISSUE THREAD

**Issue by maccam912** [HIPERFIT/futhark#144]
I made a few changes for people trying to compile on OSX. I'm not sure how to automatically detect platform and add these changes, so here is a patch file for anyone on OSX.

```
From d34694cc5a330a61dc64196c9e12f6e2a78538d9 Mon Sep 17 00:00:00 2001
From: Matt Koski <maccam912@gmail.com>
Date: Tue, 19 Apr 2016 09:19:37 -0500
Subject: [PATCH 2/2] Changes for OSX

---
 rts/c/opencl.h        | 2 +-
 src/futhark-opencl.hs | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

diff --git a/rts/c/opencl.h b/rts/c/opencl.h
index c5ca12d..3b33c7d 100644
--- a/rts/c/opencl.h
+++ b/rts/c/opencl.h
@@ -1,6 +1,6 @@
 /* The simple OpenCL runtime framework used by Futhark. */

-#include <CL/cl.h>
+#include <OpenCL/cl.h>

 #define FUT_KERNEL(s) #s
 #define OPENCL_SUCCEED(e) opencl_succeed(e, #e, __FILE__, __LINE__)
diff --git a/src/futhark-opencl.hs b/src/futhark-opencl.hs
index 2924612..8bd66dc 100644
--- a/src/futhark-opencl.hs
+++ b/src/futhark-opencl.hs
@@ -48,7 +48,7 @@ openclCodeAction filepath config =
           liftIO $ writeFile cpath cprog
           (gccCode, _, gccerr) <-
             liftIO $ readProcessWithExitCode "gcc"
-            [cpath, "-o", binpath, "-lm", "-O3", "-std=c99", "-lOpenCL"] ""
+            [cpath, "-o", binpath, "-lm", "-O3", "-std=c99", "-framework", "OpenCL"] ""
           case gccCode of
             ExitFailure code -> compileFail $ "gcc failed with code " ++ show code ++ ":\n" ++ gccerr
             ExitSuccess      -> return ()
--
2.7.1
```

**Comment by Athas** [comment]
Thanks!  I was wondering whether something like that was necessary!  I'll take a closer look at it later.  There must surely be some way to detect the OS and add the necessary flags.  Would you be available to test it?  Sadly I have no access to an OS X system.

**Comment by maccam912** [comment]
Sure. Let me know when you need me to test it!

**Comment by Athas** [comment]
I think I have found out how to do it.  You need:

```
import qualified System.Info
```

Then add a branch that checks whether `System.Info.os == "darwin"` and selects the proper compile flag.

For the header file, you need an `#ifdef __APPLE__`.

Do you want to do it (and thus have the commit in your name, which is always nice), or should I?  (In any case, I cannot test it myself, so it's probably simpler if you just do all of it.)

**Comment by maccam912** [comment]
I can do it, but I'll need to spin up a VM to test it on non-OSX.

**Comment by Athas** [comment]
If you issue a pull request, TravisCI will build it on Linux for you.

-- 
\  Troels
/\ Henriksen

**Comment by maccam912** [comment]
Resolved: https://github.com/HIPERFIT/futhark/commit/6fe48c51ed9ca5ac310e7128abe9f50d6dde77bb
