### ISSUE TITLE
Create binary releases

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#146]
Not everyone has a Haskell compiler or the patience to compile all the dependencies.  At some point, we should also create distribution packages.  As a start, we should have a simple way to create a tarball containing a `configure` script (that most importantly accepts `--prefix`) that can be used to install pre-compiled Futhark binaries.

I'm thinking about just doing this with Automake.  It seems the simplest way of getting a `configure` script, although it is massively overkill for our needs.

**Comment by Athas** [comment]
I added some tooling in 7ab1300fd2cfa0066b657493acc1f130ca8867ac.  No `configure`, but the `Makefile` reads `$PREFIX`.  Try it: http://sigkill.dk/junk/futhark-Linux-x86_64-2016-05-01.tar.xz

It even installs the manpages!

Now I just need to set up napoleon to automatically build these every day, and then point at them from the website.

**Comment by Athas** [comment]
I set up an automated script that builds a binary tarball and puts it here every day: http://futhark-lang.org/releases/

However, I'm not comfortable distributing binaries over HTTP, so I guess the next step is to setup HTTPS for the futhark-lang.org server.

**Comment by oleks** [comment]
On Sun, May 1, 2016 at 2:00 PM, Troels Henriksen <notifications@github.com>
wrote:

> I set up an automated script that builds a binary tarball and puts it here
> every day: http://futhark-lang.org/releases/
>
> However, I'm not comfortable distributing binaries over HTTP, so I guess
> the next step is to setup HTTPS for the futhark-lang.org server.
>
That is easy in this day and age.

You should also sign the binaries.

**Comment by Athas** [comment]
Can you explain how to do TLS termination with relayd?  It seems
possible, but annoying.

Signing the nightly build also seems pointless or hard, as it is
automatically generated.  Either I put my private key on napoleon (no
way), or I sign it with some special-purpose key.

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Sun, May 1, 2016 at 2:15 PM, Troels Henriksen <notifications@github.com>
wrote:

> Can you explain how to do TLS termination with relayd? It seems
> possible, but annoying.
>

No.

Signing the nightly build also seems pointless or hard, as it is
> automatically generated. Either I put my private key on napoleon (no
> way), or I sign it with some special-purpose key.


Right, for nightly builds I guess it makes less sense, but a
special-purpose key (which you can revoke), is better than no key.

**Comment by Athas** [comment]
I set up TLS at the webserver level, not with relayd.  Works now: https://futhark-lang.org/releases/

I just need to set up the cronjob for automatic refreshing of the certificate.

**Comment by Athas** [comment]
It would still be nice to get a Windows or OS X host for building snapshots.

**Comment by oleks** [comment]
On Sun, May 1, 2016 at 5:39 PM, Troels Henriksen <notifications@github.com>
wrote:

> It would still be nice to get a Windows or OS X host for building
> snapshots.
>

Yes. Would be nice for teaching and testing purposes as well.

**Comment by Athas** [comment]
So... will you be contacting SCIENCE-IT?  :-)

-- 
\  Troels
/\ Henriksen
