### ISSUE TITLE
Change tuple syntax to use parentheses

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#155]
Way back in the primordial mists of my master's thesis, I changed the syntax for tuples from the common parenthesis notation `(x,y,z)` to the present curly-braces notation `{x,y,z}`.  The reason for this was that the compiler internals, particularly fusion, would be simpler if every operation produced tuples.  This created the need for single-element tuples, and since the syntax `(x)` would be ambiguous (is it a tuple or a parenthesized expression?) I opted to change the tuple syntax to an Erlang-inspired one that could easily support that.  Since then, Futhark has split into a source and a core language, so the original motivation has become moot.

Futhark is not intended as an opinionated language.  The syntax and programming model should feel familiar.  Our present tuple syntax is definitely a departure from that philosophy.  Hence, I wish to discuss moving back to the common tuple notation that uses parentheses.  We lose one-element tuples (unless we support Python's rather ugly `(x,)` notation), but when are these really useful anyway?  This would also free up curly braces for use in records, if we ever get around to adding those.

Thoughts?

**Comment by melsman** [comment]
I'm all for it...

Den onsdag den 27. april 2016 skrev Troels Henriksen <
notifications@github.com>:

**Comment by Athas** [comment]
I am going to do this if one more person voices support.

**Comment by nqpz** [comment]
I hereby voice support!  When writing benchmarks, I always found the curly syntax a bit annoying.

**Comment by fenollp** [comment]
I voice against. (I use Erlang daily) Should have read my notifications more often!

**Comment by Athas** [comment]
Sorry, already merged. :-)
