### ISSUE TITLE
printing result on stdout

### ISSUE THREAD

**Issue by melsman** [HIPERFIT/futhark#156]
The default behaviour of running a Futhark-compiled program is to write the result on stdout with a suffix such as i32 or f32 for indicating the type of the result value. Is it possible to disable this feature or perhaps even control the format of the result printing?

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> The default behaviour of running a Futhark-compiled program is to
> write the result on stdout with a suffix such as i32 or f32 for
> indicating the type of the result value. Is it possible to disable
> this feature or perhaps even control the format of the result
> printing?

No.  Standalone execution is only for testing and is explicitly
non-configurable to reduce the fault surface.

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
Ok. I'll just modify the tail2futhark test checks to use the new syntax,
then.

Den onsdag den 27. april 2016 skrev Troels Henriksen <
notifications@github.com>:

> Martin Elsman <notifications@github.com

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> Ok. I'll just modify the tail2futhark test checks to use the new syntax,
> then.

The easiest solution is probably to just s/[fi][0-9]+//g on the output.

-- 
\  Troels
/\ Henriksen
