### ISSUE TITLE
Time for the factorial example is either 0 or 15625 on Windows.

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark#161]
I can confirm that this is not due to it being 64-bit. There is no difference between 32-bit and 64-bit versions. The time is either 0 or 15625. I am guessing that, given all that I've read about timing in that SO thread that `sys\time.h` is giving the CPU time instead of the wall clock time on Linux.

**Comment by Athas** [comment]
Futhark uses `gettimeofday()` for timing, which is wall time.  However, `gettimeofday()` is a POSIX-function, so I guess GCC on Windows must be faking it using some Windows-specific function.  My guess is that this faking does not work particularly well.

I will search around to see if this has been mentioned anywhere else, but you already convinced me of the need for some platform-portability glue in this department, so I'll see about committing a fix.

**Comment by mrakgr** [comment]
0 and 15625 in particular are fractional values. I am decently sure that the time is being converted to and from a float somewhere, which is not the expected behavior on either Linux or Windows. That SO post on timings should come in handy here.

**Comment by Athas** [comment]
I just pushed something that may help, but of course I have no idea whether the Windows-specific code even compiled.

**Comment by mrakgr** [comment]
I'll take a look.

**Comment by mrakgr** [comment]
Good work. It works.

**Comment by Athas** [comment]
Thanks for putting in all this effort!  Please report back if performance on Windows is unusually poor.
