### ISSUE TITLE
The Fibonacci loop example does not work

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark#163]
The tail recursive version works fine (and quite a bit faster than I expected,) but the loop version below does not:
```
fun int fib(int n) =
  loop ({x, y} = {1,1}) = for i < n do
                            {y, x+y}
  in x

fun int main(int n) = fib(n)
```
Regardless of n, the output is 1 with the above, but if I output y instead, it increases roughly linearly with n. 

Am I going wrong somewhere or is this a bug? I am just about done with my background reading for Futhark too.

Also, I have to ask just now, how feasible would a print statement for debugging purposes be in Futhark?

I've also tried the above in Linux to same result just to make sure this is not Windows specific.

**Comment by Athas** [comment]
Embarassing.  That is indeed a bug in some loop simplification.  I've
seen a similar case before, but I thought I had squashed it.  I'll add
that program to the test suite and come up with a fix.

-- 
\  Troels
/\ Henriksen
