### ISSUE TITLE
Race condition bug in the pared down MSS example

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark#164]
The following example only tries to do a scan operation.
```
fun int max(int x, int y) =
  if x > y then x else y

fun {int,int} redOp({int,int} x,
                    {int,int} y) =
  let {max, trace } = x in
  let {max_value, value} = y in
  { max+value
  , 0}

fun {int,int} mapOp(int x) =
  { x, x}

fun [{int,int}] main([int] xs) =
    scan(redOp, {0,0}, map(mapOp, xs))
```
Output:
```
C:\futhark\examples>futhark-opencl mss.fut

C:\futhark\examples>echo [1,2,-50,-4,5,6] | mss
[1i32, 0i32, 0i32, 0i32, 0i32, 0i32]
[0i32, 0i32, 0i32, 0i32, 0i32, 0i32]

C:\futhark\examples>futhark-c mss.fut

C:\futhark\examples>echo [1,2,-50,-4,5,6] | mss
[1i32, 3i32, -47i32, -51i32, -46i32, -40i32]
[0i32, 0i32, 0i32, 0i32, 0i32, 0i32]
```
As you can see, the sequential version executes as expected while the OpenCL does not.

I stumbled upon this while converting the maximum segment sum problem to make it a bit more readable and noticing that two of the four tuples seem to be doing nothing.

Given that the sequential and the parallel versions are different, this might be a bug, but on the other hand the full version seems to be working properly.

On the off chance that this is the correct behavior, this should definitely be documented.

**Comment by Athas** [comment]
You are quite right.  I thought I had managed to iron out all the scan
bugs, but I guess not.  I wonder why this program fails when our more
complex tests do not.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
On second thought, I am not sure that your scan operator is associative
- this means behaviour is undefined (or at least nondeterministic) when
it is executed in parallel.  Are you sure you mean to say `max+value`
and not `max+max_value`?

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
Hmmm...shouldn't both work?

Indeed, `max+max_value` works as intended, but if the first one is not supposed to then this is quite a novel definition of associativity for me. Maybe an explanation would be good? If this is the intended behavior then how this works should definitely go into the user guide.

**Comment by Athas** [comment]
Here's a simple program that demonstrates that redOp is not associative:

    fun {int,int} redOp({int,int} x,
                        {int,int} y) =
      let {max, trace } = x in
      let {max_value, value} = y in
      { max+value
      , 0}

    fun {{int,int}, {int,int}} main() =
      {redOp({1,2}, redOp({3,4}, {5,6})),
       redOp(redOp({1,2}, {3,4}), {5,6})
      }

The output is '1 0 11 0' (after removing i32 suffixes).  The first and
second pair would be identical if redOp was associative.

The user's guide does mention the associativity requirement, for example
at the end of
https://futhark.readthedocs.io/en/latest/language-overview.html: "The
functions given to reduce and scan must be binary associative operators,
and the value given as the initial value of the accumulator must be the
neutral element for the function. "

However, maybe there should be a "Futhark pitfalls" document to draw
attention to this rather subtle but extremely important requirement (and
any others like it).

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
Yeah, I see it. Sorry about the false alarm.

I guess I do not understand associativity as well as I thought I did. Previously, I thought that if + and max are there, than that would be enough to meet the requirement. The MSS example is more intricate than I thought.

**Comment by Athas** [comment]
Yeah, in my experience it is extremely easy to make things that are
non-associative by accident.  I always have to check my own functions
very carefully.

Not many parallel languages support user-defined scan/reduce-operators,
and this is probably part of reason.  It is definitely one of the sharp
features of Futhark (as in, you can end up cutting yourself if you are
not careful).

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
Actually I have one more question.
```
fun int max(int x, int y) =
  if x > y then x else y

fun {int,int} redOp({int,int} x,
                    {int,int} y) =
  let {max, trace } = x in
  let {max_value, value} = y in
  { trace
  , trace+value}

fun {int,int} mapOp(int x) =
  { x, x}

fun [{int,int}] main([int] xs) =
    scan(redOp, {0,0}, map(mapOp, xs))
```
Sample output:
```
C:\futhark\examples>echo [1,2,-50,-4,5,6] | mss
[0i32, 1i32, 3i32, -47i32, -51i32, -46i32]
[1i32, 3i32, -47i32, -51i32, -46i32, -40i32]
```
Is the above redOp function associative? It seems like it is, but I want to make sure.

Actually, the above case is something that should be definitely in the user guide, because when it come to associativity, reaching into the left side of a different tuple is not something that I've ever seen covered anywhere.

**Comment by Athas** [comment]
I copied your new redOp into my test program:

fun {int,int} redOp({int,int} x,
                    {int,int} y) =
  let {max, trace } = x in
  let {max_value, value} = y in
  { trace
  , trace+value}

fun {{int,int}, {int,int}} main() =
  {redOp({1,2}, redOp({3,4}, {5,6})),
   redOp(redOp({1,2}, {3,4}), {5,6})
  }

Running it gives '2 12 6 12', so your function is not associative.

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
Good point. But how would one go ascertaining associativity in a more complex example like the MSS?
```
fun int max(int x, int y) =
  if x > y then x else y

fun {int,int,int,int} redOp({int,int,int,int} x,
                            {int,int,int,int} y) =
  let {mssx, misx, mcsx, tsx} = x in
  let {mssy, misy, mcsy, tsy} = y in
  { max(mssx, max(mssy, mcsx + misy))
  , max(misx, tsx+misy)
  , max(mcsy, mcsx+tsy)
  , tsx + tsy }

fun {int,int,int,int} mapOp(int x) =
  { max(x,0), max(x,0), max(x,0), x }

fun [{int,int,int,int}] main([int] xs) =
    scan(redOp, {0,0,0,0}, map(mapOp, xs))
```
The `max(mcsy, mcsx+tsy)` line in particular seems like it should be non-associative as is uses the variable tsy which is the right side of the last tuple.

Also, I tried a different example like:
```
fun int max(int x, int y) =
  if x > y then x else y

fun {int,int,int,int} redOp({int,int,int,int} x,
							{int,int,int,int} y) =
  let {a1,a2,a3,a4} = x in
  let {b1,b2,b3,b4} = y in
  { a1+b1
  , a1+b2
  , a1+b3
  , a1+b4 }

fun {int,int,int,int} mapOp(int x) =
  { x, x, x, x}

fun [{int,int,int,int}] main([int] xs) =
    scan(redOp, {0,0,0,0}, map(mapOp, xs))
```
Output:
```
C:\futhark\examples>echo [1,2,-50,-4,5,6] | mss
[1i32, 3i32, -47i32, -51i32, -46i32, -40i32]
[1i32, 3i32, -47i32, -51i32, -46i32, -40i32]
[1i32, 3i32, -47i32, -51i32, -46i32, -40i32]
[1i32, 3i32, -47i32, -51i32, -46i32, -40i32]
```
It does seem like they are getting executed in tandem, but the example is non-associative. Is this effect something that I can count on or will it fail on larger examples?

**Comment by Athas** [comment]
In general, you prove associativity for Futhark functions like you would
for any mathemetical function: with hard work and rewriting.  You just
have to show that f(f(x,y),z) = f(x,f(y,z)) for all x,y,z.

You have to focus on the function *as a whole* - you should not look at
single lines by themselves, and it is okay to "cross tuples", as long as
the function as a whole is associative.

Actually, Futhark probably has a looser requirement than strict
associativity.  For scans and reductions, you just have to show that for
any *sequence* of values, you can apply the function in any order, as
long as you get the same result in the end.  I think there may be some
functions that are not stricly associative, but are "sufficiently
associative" for this.

You cannot in general assume anything of reductions or scans with
non-associative operators.  If they are executed sequentially, you will
get strict left-to-right application, but the parallel code generator
depends heavily on being able to re-organise the order of application.

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
Yeah, I've tested both MSS and the above example and it seems that they are both associative.
```
fun int max(int x, int y) =
  if x > y then x else y

fun {int,int,int,int} redOp1({int,int,int,int} x,
							{int,int,int,int} y) =
  let {a1,a2,a3,a4} = x in
  let {b1,b2,b3,b4} = y in
  { a1+b1
  , a1+b2
  , a1+b3
  , a1+b4 }

fun {int,int,int,int} redOp({int,int,int,int} x,
                            {int,int,int,int} y) =
  let {mssx, misx, mcsx, tsx} = x in
  let {mssy, misy, mcsy, tsy} = y in
  { max(mssx, max(mssy, mcsx + misy))
  , max(misx, tsx+misy)
  , max(mcsy, mcsx+tsy)
  , tsx + tsy }

fun {int,int,int,int} mapOp(int x) =
  { x, x, x, x}

fun {{int,int,int,int},{int,int,int,int}} main([int] xs) =
    {redOp({1,2,3,4},redOp({5,6,7,8},{9,10,11,12})),
	 redOp(redOp({1,2,3,4},{5,6,7,8}),{9,10,11,12})}
```
Actually, I found this surprising. I guess that from here, I will be adding proving associativity to my programming arsenal.

I still do not understand tuple crossing, but I will keep playing with it. Thank you for explaining.

**Comment by mrakgr** [comment]
Sorry, I thought I was done but I have another example I cannot figure out.
```
type tup = {int, int}

fun int max(int x, int y) =
  if x > y then x else y

fun tup redOp(tup x,
			  tup y) =
  let {a1,a2} = x in
  let {b1,b2} = y in
  { a1+b1
  , max(0,max(a1,a2))+b2 }

fun tup mapOp(int x) =
  { x, x}

fun bool is_associative(tup a, tup b, tup c) =
	let {r1,r2} = redOp(redOp(a,b),c)
	let {t1,t2} = redOp(a,redOp(b,c)) in
	(r1 == t1 ) && (r2 == t2)


fun [tup] main([int] xs) =
	if is_associative({1,2},{3,4},{5,6}) && is_associative({1654,210},{39877,4324654},{51,1})
	then scan(redOp, {0,0}, map(mapOp, xs))
	else [{666,666}]
```
Output:
```
C:\futhark\examples>echo [1,2,-50,-4,5,6] | mss
[1i32, 3i32, -47i32, -51i32, -46i32, -40i32]
[1i32, 3i32, -47i32, -4i32, 5i32, 12i32]
```
I cannot figure out where that 12 at the lower right is coming from for the life of me.
`max(0,max(-45,5))+6=11`

Just where is that `7` coming from? I cannot believe this.

`futhark-c` version works as expected.

**Comment by mrakgr** [comment]
This example is informative:
```
type tup = {int, int, int}

fun int max(int x, int y) =
  if x > y then x else y

fun tup redOp(tup x,
			  tup y) =
  let {a1,a2,a3} = x in
  let {b1,b2,b3} = y in
  { a1+b1
  , max(0,max(a1,a2))+b2
  , a2 }

fun tup mapOp(int x) =
  { x, x, x}

fun bool is_associative(tup a, tup b, tup c) =
	let {r1,r2,r3} = redOp(redOp(a,b),c)
	let {t1,t2,t3} = redOp(a,redOp(b,c)) in
	(r1 == t1 ) && (r2 == t2) && (r3 == t3)


fun [tup] main([int] xs) =
	if True || (is_associative({1,2,123},{3,4,234},{5,6,456}) && is_associative({1654,210,519},{39877,4324654,124},{51,1,127}))
	then scan(redOp, {0,0,0}, map(mapOp, xs))
	else [{666,666,666}]
```
Output:
```
C:\futhark\examples>echo [1,2,-50,-4,5,6] | mss
[1i32, 3i32, -47i32, -51i32, -46i32, -40i32]
[1i32, 3i32, -47i32, -4i32, 5i32, 12i32]
[1i32, 1i32, 3i32, -47i32, -1i32, 6i32]
```
The above example fails the associativity check, so I've left it out on purpose, but it seems there are some data races in the above post. Note how in the lower right in the last two positions it stores -1 and 6 instead of -4 and 5 as one would expect.

Is this a bug or is my associativity check simply insufficient?

**Comment by Athas** [comment]
You've run into the other requirement, apart from associativity: you
must provide a neutral element.  {0,0} is not a neutral element for those
functions.

Think of these annoying rules as a tax you pay in return for performance. :-)

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
I was surprised by your reply 10m ago and I still cannot see it. {0,0} seems pretty neutral to me. It even passes the associativity check.

Would you mind explaining?

**Comment by Athas** [comment]
Demonstration for your latter program:

    type tup = {int, int, int}

    fun int max(int x, int y) =
      if x > y then x else y

    fun tup redOp(tup x,
                  tup y) =
      let {a1,a2,a3} = x in
      let {b1,b2,b3} = y in
      { a1+b1
      , max(0,max(a1,a2))+b2
      , a2 }

    fun {tup, tup} main() =
      let ne = {0,0,0}
      let x = {1,2,3}
      in {x, redOp(x, ne)}

If 'ne' is a neutral element, then 'redOp(x, ne)' should be equal to 'x'.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
(And 'redOp(ne, x)' too, for that matter.)

**Comment by mrakgr** [comment]
I was going to say that then {0,0,0,0} is not the neutral element for the MSS example, but then I remembered that its inputs come in `{ max(x,0), max(x,0), max(x,0), x }` form. It does seem to be the neutral element for those types.

...I am still thinking about this. Think kind of programming is not something I've ever done before. Where can I learn more about this?

Also, for my program, is there even a neutral element for all valid inputs (in the `{ max(x,0), max(x,0), max(x,0), x }` form)? If so, how do I figure out what it is?

Sorry for the barrage of questions, but on the up side, they should definitely be in the user guide.

**Comment by Athas** [comment]
This is not a natural form of programming for most people.  In fact, I'm
not sure it has ever been mainstream - the ideas behind it are old (the
structure with an associative operator and neutral element is called a
monoid), but they weren't important to programming until they turned out
to be crucial to many parallelisation problems.  I'm not sure anyone has
ever written a textbook on programming hints for this kind of stuff.

There is no systematic way of finding a neutral element that I know of.
It just requires creativity.  Most likely you will have to tweak your
data representation to ensure that a neutral element is possible.  I
think some of the elements of the MSS tuple are there solely to ensure
this.

You are definitely right that we should have some sort of document that
introduces these things, and maybe provides some hints and examples.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
I realised that you can always define a neutral element by adding an additional field to your tuple of type `bool`.  Make the operator check this field and treat the value as a neutral element if it is true.

It's a little ugly, but will always work, I think.

**Comment by mrakgr** [comment]
Interesting. I played a bit with the MSS example, and the second line `max(misx, tsx+misy)` seems to be doing absolutely nothing. The `max(mssx, max(mssy, mcsx + misy))` which line does not reference its past results in any way, but trying to modify it makes the associativity tests fail. Also the outer `max(mssx, ...)` seems to be completely unnecessary, but removing it makes the associativity tests fail as well.

I do not understand it at all.
