### ISSUE TITLE
Mandelbrot example does not work without an extra conversion to a Numpy array

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark#169]
```
...
miny=-1.15
maxx=0.83
maxy=1.15
fut_image=m.main(width, height, limit, minx, miny, maxx, maxy).get()
```
In connection to #165, the Mandelbrot example needs an extra conversion from a pyOpenCL to a standard Numpy array to work for me on Windows. With this it works fine. I can also confirm the the `pypng` writer works once this step has been done.

**Comment by Athas** [comment]
I was wondering if this might come back to bite us.  PyOpenCL attempts
to be Numpy-compatible with its arrays, but the exact degree of
compatibility seems to be dependent on platform.

I've added an explicit .get().  Can you verify that it works?

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
(I assume you meant the Mandelbrot example on the devblog.)

**Comment by mrakgr** [comment]
Yeah, I meant on the devblog. It works. Good job.
