### ISSUE TITLE
'entry' keyword is undocumented

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark#170]
I just noticed this new thing in while looking at the `life.fut` for the Conway's Game of Life example. No mention of it in the documentation.

Looking at the generated code for the Python modules and C programs, I am guessing this just makes the function callable from the outside. I was wondering about this feature before actually, it is convenient that it is here.

Is there anything special about it or not obvious at first glance?

**Comment by Athas** [comment]
Nope, that's what it does.  I'll add it to the language reference, but
we should also create a general documentation page on compiling as a
module.  Maybe create issues for our documentation plans?


-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
As far as I know only `pyopencl` can create modules now, right? I am not sure if there is too much to go on here.

**Comment by Athas** [comment]
Right, but it's the prototype for how I think all backends should work.
The idea behind the 'entry' keyword is certainly here to stay.  The
caveats about entry point types may also be worth documenting.


-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
Of course. At least, the `--option` for `futhark-pyopencl` should be documented.

Actually, now that I've gotten everything there is to work, I think I will make a Futhark Windows/Cuda installation guide. Stay tuned.
