### ISSUE TITLE
Windows installation guide

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark#171]
This guide written in 5.5.2016 is for computers using 64-bit Windows along with [Cuda 7.5](https://developer.nvidia.com/cuda-downloads) and Python 2.7 ([Anaconda](https://www.continuum.io/downloads#_windows) preferred.)

1) Fork and clone the Futhark repository to your hard drive.

2) Install [Stack](http://docs.haskellstack.org/en/stable/install_and_upgrade/#windows) using the 64-bit installer.

3) For editing environment variables it is strongly recommended that you install the [Rapid Environment Editor](http://www.rapidee.com/en/about)

4) For a Futhark compatible C/C++ compiler that you will also need to install pyOpenCL later, install MingWpy. Do this using the `pip install - i https ://pypi.anaconda.org/carlkl/simple mingwpy` command.

5) Assuming you have the latest Anaconda distribution as your primary one, it will get installed to a place such as `C:\Users\UserName\Anaconda2\share\mingwpy`. The pip installation will not add its bin or include directories to path.

To do so, open the Rapid Environment Editor and add `C:\Users\UserName\Anaconda2\share\mingwpy\bin` to the system-wide PATH. 

If you have other MingW or GCC distributions, make sure MingWpy takes priority by moving its entry above the other distributions. You can also change which Python distribution is the default one using the same trick should you need so.

If have done so correctly, typing `where gcc` in the command prompt should list the aforementioned MingWpy installation at the top or show only it.

To finish the installation, add the `C:\UserName\Marko\Anaconda2\share\mingwpy\include` to `CPATH`. Create the variable if necessary.

6) The header files and the .dll for OpenCL that come with the Cuda 7.5 distribution also need to be installed into MingWpy. Go to `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v7.5\include` and copy the `CL` directory into the MingWpy `include` directory.

Next, go to `C:\Program Files\NVIDIA Corporation\OpenCL` and copy the `OpenCL64.dll` file into the MingWpy `lib` directory (it is next to `include`.)

The Cuda distribution also comes with the static `OpenCL.lib`, but trying to use that one instead of the `OpenCL64.dll` will cause the `futhark-opencl` compiled programs to crash, so ignore it completely.

Now you should be able to compile `futhark-opencl` and run Futhark programs on the GPU.

Congratulations!

---
7) The following instructions are for how to setup the `futhark-pyopencl` backend.

First install Mako using `pip install mako`.

Also install Pypng using `pip install pypng`.

8) Clone and fork the [pyOpenCL](https://github.com/pyopencl/pyopencl) to hard drive. Do this instead of downloading the zip, as the zip will not contain some of the other repositories it links to and you will end up with missing header files.

9) If you have ignored the instructions and gotten Python 3.x instead 2.7, you will have to do some extra work. 

Edit ".\pyopencl\compyte\ndarray\gen_elemwise.py" and ".\pyopencl\compyte\ndarray\test_gpu_ndarray.py" and convert most Python 2.x style print statements to Python 3 syntax. Basically wrap print arguments in brackets "(..)" and ignore any lines containing StringIO ">>" operator. 

Otherwise just go to the next point.

10) Go into the repo directory and from the command line execute `python configure.py`.

Edit `siteconf.py` to following:
```
CL_TRACE = False
CL_ENABLE_GL = False
CL_INC_DIR = ['c:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5\\include']
CL_LIB_DIR = ['C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v7.5\\lib\\x64']
CL_LIBNAME = ['OpenCL']
CXXFLAGS = ['-std=c++0x']
LDFLAGS = []
```
Run the following commands:
> python setup.py build_ext --compiler = mingw32
> python setup.py install

If everything went in order, pyOpenCL should be installed on your machine now.

11) Lastly, pyGame needs to be installed. To do so on Windows, download `pygame-1.9.2a0-cp27-none-win_amd64.whl` from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygame). `cp27` means Python 2.7 and `win_amd64` means 64-bit Windows.

Go to the directory you have downloaded the file and execute `pip install pygame-1.9.2a0-cp27-none-win_amd64.whl` from the command line.

Now you should be able to run the [Mandelbrot Explorer](https://github.com/HIPERFIT/futhark-benchmarks/tree/master/misc/mandelbrot-explorer) and and [Life](https://github.com/HIPERFIT/futhark-benchmarks/tree/master/misc/life) examples.

12) To run the makefiles, first setup `make` by going to the `bin` directory of MingWpy and making a copy of `mingw32-make.exe`. Then simply rename `mingw32-make – Copy.exe` or similar to `make.exe`. Now you will be able to run the makefiles.

13) This guide has been written off memory, so if you are having difficulties - ask on the issues page. There might be errors in it.

**Comment by mrakgr** [comment]
By the way, @nqpz has been really eager in modifying the Mandelbrot Explorer and Life examples to the new tuple syntax so strictly speaking, right now the guide won't work for it unless the user downloads the previous commit. How is the new syntax coming along?

**Comment by Athas** [comment]
Nice!  Do you want this added to futhark.readthedocs.io?  And if so, do
you want to it yourself
(https://github.com/HIPERFIT/futhark/tree/master/docs) and issue a pull
request?  If not, I'll take care of reformatting and making the commit.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
It went in yesterday.

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
I'd prefer if you decide where to put it. Please do so.

**Comment by Athas** [comment]
It's here now: https://futhark.readthedocs.io/en/latest/windows-installation.html

Linked from the front page and the generic installation instructions.

Thanks for the guide!

**Comment by mrakgr** [comment]
Good work.

**Comment by Athas** [comment]
Well, you're the one who did the work.

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
To be honest, I hadn't known how to add it to the docs until I saw how you did it in the commit. That saved me a bit of time and brain energy. So thanks for that.
