### ISSUE TITLE
Difficulty getting the fluid example to run on Windows

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark#172]
I thought I was done, but no such luck. I am having difficulty figuring out how to get the [Fluid example](https://github.com/HIPERFIT/futhark-benchmarks/tree/master/accelerate/fluid) to run.

I managed to get as far as figuring out how to use a bash shell in Windows - Github for Windows provides one, but when I try to run the script like so for example it fails.
```
$ bash fluid-make-images.sh 1 600 "futhark" @"C:\!im" 42
bash: fluid-make-images.sh: No such file or directory
```
I found the first problem with the above just now.

```
Run `./fluid-make-images.sh <n steps> <grid resolution> <backend> <output
directory> <seed>` to make `<n steps>` images of size `<grid resolution> × <grid
resolution>` with the `<backend>` `futhark` or `c`, and with the random seed
`<seed>` as a predefined number or as `none`.
```
```
n_steps="$1"
grid_resolution="$2"
n_solver_steps="$3"
backend="$4"
out_dir="$5"
seed="$6"
```
The readme does not mention the n_solver_steps argument at all.

After I fixed that, I tried the following command.
```
Marko@Lain MINGW64 ~/Documents/Visual Studio 2015/Projects/futhark-benchmarks/accelerate/fluid/visualize (master)
$ bash fluid-make-images.sh 1 600 1 "futhark" "asd" 42
error: there is no fluid-visualize-densities program
```
I ran `make all` in gui directory and then after that compiled all the files in `src-futhark` manually. After that I tried the above command again.
```
Marko@Lain MINGW64 ~/Documents/Visual Studio 2015/Projects/futhark-benchmarks/accelerate/fluid/visualize (master)
$ bash fluid-make-images.sh 1 600 1 "futhark" "asd" 42
/usr/bin/env: python3: No such file or directory
/usr/bin/env: python3: No such file or directory
C:\Users\Marko\Documents\Visual Studio 2015\Projects\futhark-benchmarks\accelerate\fluid\src-futhark\fluid-visualize-densities.exe: Syntax error when reading [[f32]].
```
Futhermore, compiling the files in `src-c` also fails.
```
C:\Users\Marko\Documents\Visual Studio 2015\Projects\futhark-benchmarks\accelerate\fluid\src-c>make all
gcc -O3 -Wall -Wextra -pedantic -Werror -std=c99 -c solver.c
gcc -O3 -Wall -Wextra -pedantic -Werror -std=c99 -o fluid-visualize-densities fluid-visualize-densities.c solver.o
fluid-visualize-densities.c: In function 'draw_all_frames':
fluid-visualize-densities.c:33:3: error: unknown conversion type character 'z' in format [-Werror=format=]
   printf("%zd\n", N);
   ^
fluid-visualize-densities.c:33:3: error: too many arguments for format [-Werror=format-extra-args]
fluid-visualize-densities.c: In function 'main':
fluid-visualize-densities.c:44:3: error: unknown conversion type character 'z' in format [-Werror=format=]
   scanf("%zu", &N);
   ^
fluid-visualize-densities.c:44:3: error: too many arguments for format [-Werror=format-extra-args]
cc1.exe: all warnings being treated as errors
makefile:10: recipe for target 'fluid-visualize-densities' failed
make: *** [fluid-visualize-densities] Error 1
```
```
C:\Users\Marko\Documents\Visual Studio 2015\Projects\futhark-benchmarks\accelerate\fluid\src-c>make clean
rm -f fluid-visualize-densities fluid-benchmark fluid-demo solver.o timing.o
process_begin: CreateProcess(NULL, rm -f fluid-visualize-densities fluid-benchmark fluid-demo solver.o timing.o, ...) failed.
make (e=2): The system cannot find the file specified.
makefile:25: recipe for target 'clean' failed
make: *** [clean] Error 2
```
Currently, the example scripts use way too much Linux specific stuff to be portable. I'll try figuring out why `make clean` is failing at least and removing the -pedantic flag.

**Comment by Athas** [comment]
You're trying to run some old-ish code that we put in place before we
could use Pygame.  It works by creating image files that are then
stiched together using nasty shell scripts.  Instead of trying to make
sense of the stuff in the "visualize" directory, I recommend you try the
"gui" directory instead.  The code in there is written much like the
Mandelbrot Explorer, and uses Pygame.

Maybe we should have a warning here.  @nqpz?

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
Ok, I figured out why `make clean` suddenly stopped working. It seems like that chmod error, msys functions from the library I had can easily get corrupted. The solution is to use a much better set of Linux command line tools that come with Git for Windows. I am going to have a pull request with some extra instructions for the Windows install soon.

Apart from that `src-c` refuses to compile. Messing with flags go me a bit further, and in fact I seem to be missing a header in the GL directory, which I am guessing is shorthand OpenGL. 

I am guessing that this is the Rodinia example? If so, maybe I can just leave that one alone as I am more interested in getting the Futhark parts working.

**Comment by Athas** [comment]
Src-c is just the original C code that we ported to create the fluid
benchmark.  Don't bother trying to get it to work.  We didn't write it -
it's just included for reference.

-- 
\  Troels
/\ Henriksen

**Comment by mrakgr** [comment]
Yeah, it seems that just running `make` and then `python fluid-gui.py 256` in the command line is enough to get this to work.

I strongly suggest that you add a warning as suggested. I spent quite a bit of time trying to get the other things to work for no reason it seems.

**Comment by Athas** [comment]
@nqpz, I suggest you just delete those folders.

-- 
\  Troels
/\ Henriksen

**Comment by nqpz** [comment]
Ah, yes.  My great shell scripts.  I agree that they are superseded by the fancy fluid simulation GUI.  Removed in commit f3a7feaa85f0d221163e3c0c4badf7641a30c7b6.

**Comment by mrakgr** [comment]
Should have closed this yesterday, as I no longer have any problems getting it to run. My backlog is growing and in addition, the fluid example is quite larger than expected, so it will take a me a few days until I finish studying it and can move to the next example.
