### ISSUE TITLE
Why do we have both 'fun' and 'fn'?

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#174]
We use `fun` for top-level functions and `fn` for anonymous functions.  What will we use when we add local functions?  Why do we have two different keywords to begin with?

**Comment by fenollp** [comment]
2 cents: the grammar may not even need `fun` for top-level functions

**Comment by Athas** [comment]
No, I'm thinking the same thing.  There is no ambiguity I can see.

-- 
\  Troels
/\ Henriksen
