### ISSUE TITLE
Shape checking bug in pyopencl backend

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark#177]
```
entry [[f32,m],n]
                 test([[f32,o],m] W_bi, [f32,m] b_bi, 
					  [[f32,n],o] input) =
	linear_layer(W_bi,input,b_bi)
```
The function being called looks like the above in Futhark code.  
```
  def test(self, W_bi_mem_5047_ext, b_bi_mem_5049_ext, input_mem_5051_ext):
    m_4573 = np.int32(W_bi_mem_5047_ext.shape[np.int32(0)])
    o_4574 = np.int32(W_bi_mem_5047_ext.shape[np.int32(1)])
...
```
On the Python end it looks like the above. `input_mem_5051_ext` specifically corresponds to the 1D numpy array of the bias vector.  Just like for the 2D matrices, it tries to get the shape of the second dimension and throws an exception.
```
    print "Hello."
    print input_mem_5051_ext.shape
    o_4574 = np.int32(input_mem_5051_ext.shape[np.int32(0)])
    n_4575 = np.int32(input_mem_5051_ext.shape[np.int32(1)]) # It throws an index out of bounds exception here.
```
This is just the start of it, I am trying to run the whole LSTM cell ([from the other issue](https://github.com/HIPERFIT/futhark-benchmarks/issues/4)) and depending on the size of the inputted matrices, it throws different exceptions. **(Edit: Those were fixed with the shape annotations.)**

I've pushed the examples on my own [branch](https://github.com/mrakgr/futhark/tree/master/examples/lstm%20cell) if you want to take look.

**Comment by Athas** [comment]
To me it looks like it's trying to check the shape of the `W_bi` array, which is indeed supposed to be two-dimensional.  Do you have a minimal self-contained test case?

**Comment by mrakgr** [comment]
```
W_bi = np.random.random((hidden_size, input_size)).astype(np.float32)
b_bi = np.random.random((hidden_size)).astype(np.float32)
input = np.random.random((input_size,batch_size)).astype(np.float32)
output = c.test(W_bi,input,b_bi)
```
```
entry [[f32,m],n]
                 test([[f32,o],m] W_bi, [f32,m] b_bi, 
					  [[f32,n],o] input) =
	linear_layer(W_bi,input,b_bi)
```
Ok, so here is why I am getting the error. In, the `output = c.test(W_bi,input,b_bi)` the input is in the wrong place. My bad. Sorry about that.

**Comment by Athas** [comment]
I suppose we could improve the generated Python code to check that the rank is as expected, and give a friendlier error message if not.
