### ISSUE TITLE
Do in-place-lowering (or equivalent) when sequentialising loops

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#20]
Consider this program:

````
fun [[int]] main([int] a, [[int]] contribs) =
  scan( fn [int] ([int] x, [int] y) => zipWith(op +, x, y)
      , a
      , contribs
      )
````

Our strategy for compiling this is to sequentialise it into do-loops, then perform in-place lowering to remove memory copies.  Unfortunately, due to the loss of information about the memory access pattern of the inner `map`, the optimiser is not able to make it fully in-place:

````
      let {*[int,size_31] result_44} = scratch(int, size_31) in
      // Consumes result_44
      let {*[int,size_31] res_53} =
        loop {*[int,size_31] map_outarr_47} <- {*[int,size_31] map_outarr_47} = {result_44}
        for i_48 < size_31 do
          let {int x_49} = acc_39[i_48] in
          let {int y_50} = fold_arr_40[i_41, i_48] in
          let {int res_51} = x_49 + y_50 in
          // Consumes map_outarr_47
          let {(*[int,size_31] lw_dest_52 <- map_outarr_47)[i_48]} = res_51 in
          {lw_dest_52} in
      // lw_dest_54 aliases res_53
      // Consumes fold_arr_40
      let {(*[[int,size_31],size_30] lw_dest_54 <- fold_arr_40)[i_41]} = res_53 in
````

Note that `fold_arr_40` is used inside the loop, and is the source in the following in-place update.  Of course, we could do loop parallelism analysis on the loop to figure out whether lowering is safe anyway and fix up the array accesses, but it feels really ridiculous to try to re-acquire knowledge that was completely apparent in the original `map`.

Instead, the solution is to be smarter when turning SOACs into do-loops.  Specifically, I want to do in-place lowering at the very spot the transformation is done.  I want to say "turn this `map` into a do-loop, and put the result at row `a[i]`" - which means that we can modify the generated loop to write to `a[i,j]` in iteration `j`.  This would require a significant increase of intelligence and complexity in the first-order-transformer, but it seems like a fairly critical component anyway, so I believe this is justified.

**Comment by Athas** [comment]
I actually lost sleep over this one.

**Comment by coancea** [comment]
>> Instead, the solution is to be smarter when turning SOACs into 
do-loops.
 >> Specifically, I want to do in-place lowering at the very spot the 
transformation is done.
 >> I want to say "turn this |map| into a do-loop, and put the result at 
row |a[i]|" - which means
 >> that we can modify the generated loop to write to |a[i,j]| in 
iteration |j|.

Agreed! This and sequential fusion should take care of it.

However, there are still bugs in the code: the C compiled code does
not give the same result as the futhark interpreted version.

Should I take a closer look to identify the problem?

Cosmin
