### ISSUE TITLE
Extend 'include' functionality with 'as' statement

### ISSUE THREAD

**Issue by MikkelStorgaard** [HIPERFIT/futhark#200]
Currently `include MyModule` simply combines the declarations from MyModule.fut with the declarations in the main program, before passing this on to the type checker.

It would be desirable to enable an as-statement, so that `include MyModule as MyModule` includes the declarations from MyModule _into a structure_ in the main program, so the declarations in MyModule can be accessed using dot-notation, such as `let x = MyModule.foo(2)`

**Comment by Athas** [comment]
This is a sound design.  I have been thinking about how include should
interact with modules, and this is also what I came up with.  It is
simple and flexible.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
This was done (albeit in another way) when file inclusion was re-implemented.
