### ISSUE TITLE
Bad error message when array-of-tuples to tuple-of-arrays transformation fails

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#21]
When running `futhark` on this
```
fun [ { [int], [int] } ] main () =
    [ {[1,2], [3,4,5]}, {[4], [1,2,3,4]} ]
```
I get the cryptic error message `futhark: (Array.!): undefined array element`. This is of because of the array-of-tuples to tuple-of-arrays transformation, which is also shown in the documentation, but I still think a better error message could be expected.

---

lets also get a way to add negative tests

**Comment by Athas** [comment]
This fails due to changes I recently made in `Futhark.Internalise.TypesValues.internaliseValue`.  (I think previously it just naively truncated, so no great regression.)  I will fix it eventually.
