### ISSUE TITLE
Replace size with shape

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#214]
For a long time, we have had a `size` construct that picks out the size of a specific dimension.  This has its roots in the time when we did not have a separate source and core language.  Now, `size` is kind of weird.  Instead, we should have a `shape` that returns either an array or a tuple of all the dimension sizes.  I'm leaning towards a tuple.

**Comment by melsman** [comment]
.. but if rank polymorphism is getting to work with modules, for instance,
the shape function would need to return a vector of ints...

**Comment by Athas** [comment]
You can just make size-polymorphic tuples too!

The advantage of using tuples is that you can nicely extend `shape` to handle arrays nested inside tuples too.  E.g, if `x : []([](int,[]int),[]int)`, then `shape(x) : (int, ((int, int), int)`.
