### ISSUE TITLE
Support for ℂ numbers

### ISSUE THREAD

**Issue by fenollp** [HIPERFIT/futhark#217]
I couldn't find mention of ℂ numbers in [the language ref](https://github.com/HIPERFIT/futhark/blob/master/docs/language-reference.rst#language-reference).

Types notation: I suggest `c64`, `c128`.

Although right now I have no requirements wrt bit precision, I would like [the operations mentioned in this paper](http://arxiv.org/abs/1503.03438) implemented.
(e.g. `pow(complex, int)`, `sqrt(complex)` if pow doesn't do it & `abs(complex)`)

**Comment by Athas** [comment]
I'm not sure there is a need for complex numbers in the language itself.  They would be mapped to pairs of floats in the code generator anyway, wouldn't they?  I'm not aware of any machine that can handle complex numbers in a more efficient fashion.

Of course, for complex numbers to be (conveniently) implementable as a library, we would need to support operator overloading.  This is planned anyway.  Currently you have to write some fairly awkward code, like I did in this Mandelbrot implementation: https://github.com/HIPERFIT/futhark-benchmarks/blob/master/misc/mandelbrot-explorer/mandelbrot.fut

It's clumsy, but it performs very well, so I think this is mostly a question of how to support more syntactical niceties.

**Comment by fenollp** [comment]
I think having complex numbers in the language would greatly help the ecosystem. (Instead of everyone rolling their own more or less buggy things).
Anyway this sounds like a "should this really be part of prelude/stdlib", which actually raises a question: are there any plans for a stdlib of some kind?

It can just mean `type c64 = (f32, f32)` for OpenCL (btw PyOpenCL seem to have complex numbers).
If CUDA [seem to have complex numbers too](https://github.com/pathscale/nvidia_sdk_samples/blob/master/matrixMulCUBLAS/build/cuda/5.0.35-13978363_x64/include/cuComplex.h#L60) it looks like for now, at least, they are pairs of floats/doubles.

As I understand the goal of futhark is to be able to target different hardware with the same code. Maybe this also means different language backends?
I.e if targeting CPUs & using the Go backend then complex numbers would almost map 1:1 (since golang has `complex128`).

**Comment by Athas** [comment]
Yes, some form of stdlib is definitely planned.  We postponed it until we had a rough module system, which we do now.  We still don't have any form of polymorphism, which makes things a little awkward, but maybe we should just get started...  Complex numbers would definitely have a place in that library.

I'm pretty sure Go also just maps complex numbers to pairs of floats.  It's not that I'm opposed to complex numbers in the language if there was a significant benefit, but if we can implement them as a library (maybe even use it as inspiration for library support in Futhark), that would save us from having to add a bunch of complexity to the compiler.

**Comment by Athas** [comment]
Now that we have a module system, I am drafting out a signature for complex numbers:

```
module type COMPLEX {
type real
type complex

val mk: real -> real -> complex
val conj: complex -> complex
val re: complex -> real
val im: complex -> real

val add: complex -> complex -> complex
val sub: complex -> complex -> complex
}
```

More operations are necessary, of course.  But this kind of stuff *really* calls out for user-defined operators.  Maybe we'll have to do them soon.
