### ISSUE TITLE
A few comment typos in source

### ISSUE THREAD

**Issue by mrakgr** [HIPERFIT/futhark#219]
This issue is really trivial, but since I found them I might as well report them.

```
-- | Alias for a tagged 'Name'.  This is used as the name
-- representation in most the compiler.
```

In `Core.hs`. `in most the` should be `in most of the`. On line `153`.

```
            -- Second arg is the type of of the rows of the array (not
            -- the element type).
```

This is in `Syntax.hs` on line 380. `of of` rows should be just a single `of`. 

```
data TypeDefBase f vn = TypeDef { typeAlias :: Name -- Den selverklærede types navn
                                , userType :: TypeDeclBase f vn -- type-definitionen
                                , typeDefLocation :: SrcLoc
                                }
```

Some Danish comments in `Syntax.hs`. Probably someone left it in while working late and did not bother to change it. This is on line `621`.

```
-- | Signed integer exponentatation.
doPow :: IntValue -> IntValue -> IntValue
doPow v1 v2 = intValue (intValueType v1) $ intToInt64 v1 ^ intToInt64 v2

-- | Floating-point exponentatation.
doFPow :: FloatValue -> FloatValue -> FloatValue
doFPow v1 v2 = floatValue (floatValueType v1) $ floatToDouble v1 ** floatToDouble v2
```

This is on line 504 of `Primitive.hs`.  `exponentatation` should be `exponentiation`. This typo is in two lines.

I was not looking particularly carefully for these things, they just caught my eye. I probably missed some. At any rate, I think I have a decent overview of how the first part of Futhark is organized. From here the plan will be to learn a little about Haskell build tools and then piece together a basic parse example. In `Parser.hs` there is a function (or a few) that takes in the code as a string and returns an AST so I will focus on that.

Also, not everything in the first part is in the languages folder. Most noteworthy the `Primitives.hs` file which is referenced in `Syntax.hs` is in the `Representation` folder. Some of the files seem to reference `Util/Pretty.hs` as well. The `Primitives.hs` file seems to be the root of Futhark at any rate.

One thing that stuck out at me as I read the source is how most function are at the top level, while the rest is at most one level deep in terms of nesting. In contrast, in my own F# programming I often nest functions to isolate them from the rest.

I am guessing that this shallow nesting style is good at facilitating rapid development from the REPL. In contrast, with deep nesting one would have to rely a lot more on the IDE. I think I understand a lot better now why none of the Futhark devs seem to be favoring high tech tools in particular. It might be interesting to try coding like that myself.

As usual, I'll go at this bit by bit.

**Comment by Athas** [comment]
Thank you for your report!  We strive for perfection, so every report, no matter how minor, is welcome.

You are right about Language having a dependency on Primitive - I forgot about that.  My intent was for Language to be standalone (possibly even factored into its own package), but some things are just convenient to share.  I would move Primitive to Language, but Language only uses very few things from that module (the primitive values, IIRC).

The shallow nesting of functions is fairly common in Haskell programs, as Haskell does not have the `local` keyword from SML (and I guess F#?).

**Comment by mrakgr** [comment]
No, F# does not have the `local` keyword, all functions/variables/expressions are locally scoped. It has the `global` keyword, but that just has to do with .NET namespaces.
