### ISSUE TITLE
futhark-bench enhancements

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#220]
We are writing an optimising compiler, but it is still too hard for us to measure the impact of our changes.  One important step towards solving this is to make `futhark-bench` able to record its results in a machine-readable format.  I suggest the following steps be taken:

1. Make `futhark-bench` able to process several input programs, just like `futhark-test` does it.

2. Add a `--json` flag to `futhark-bench` that makes it write a result summary (raw runtimes plus median runtimes for every program and dataset).

3. Write a tool (doesn't have to be in Haskell, could be in Python) that takes as input two JSON files produced by `futhark-bench` and prints a short report of the changes, for example percentage-wise speedup/slowdown for every program and dataset.

Then, when we embark on some horrible task like implementing (or improving) loop tiling, we can do an initial run of our benchmark suite, save the JSON results, and compare to them when we want to see the impact of our work.  This would help a lot with noticing regressions, as all this is presently a manual process.

**Comment by fenollp** [comment]
Ref could be CI servers.
You guys could also use CircleCI (or another) which has more run time & cores & RAM also for free. Could help bench while travis runs tests & gain time on iterations(PRs, commits)!

**Comment by Athas** [comment]
Definitely, in the longer run we need to set up some CI on our own GPU
machines.  We already had some students develop a promising prototype,
but it lacks a data model for results (and is awkward for the use case I
described above).  That's why I'm trying a bottom-up approach this time.

-- 
\  Troels
/\ Henriksen
