### ISSUE TITLE
New Filter Semantics

### ISSUE THREAD

**Issue by coancea** [HIPERFIT/futhark#23]
Internal Futhark:

filter :: (a->bool, ..., a->bool, [a]) -> 
           (int,         ..., int,         [a])

External Futhark:

filter :: (a->bool, ..., a->bool, [a]) ->
           ([a],         ..., [a],         [a])

Semantics (External Futhark):
    input:    n conditions and an array
    output:  n + 1 arrays, such that the first one contains only the 
                 original-array elements that succeed under the first condition, ...,
                 and the last (n+1th) array contains the array elements that failed
                 under all conditions.

**Comment by Athas** [comment]
This has turned out to be more complicated, as we need a solution that works well with fusion.

**Comment by Athas** [comment]
I have done the first part of this (adding a generalised partition to the internal language), and am now working on the external language.

**Comment by Athas** [comment]
In the external language, I am going to preserve the existing `filter` semantics, but add a new SOAC - `partition` - that performs multi-way filtering.
