### ISSUE TITLE
Add global constants to source language

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#230]
It is a bit silly that constants have to be defined as unit functions, as here from HotSpot:

```
fun max_pd(): f32 = 3.0e6
```

We should support a simple ML-like notation instead:

```
val max_pd: f32 = 3.0e6
```

For simplicity, we will keep them as unary functions in the core language.  Inlining will take care of it.  The only complexity is that the type checker should ensure that there are no circular value definitions (directly or indirectly).

**Comment by fenollp** [comment]
What happens if such a declaration is written from inside a function definition?

**Comment by Athas** [comment]
Syntax error.  Inside a function you'd just use a normal `let` binding instead.

I suppose we could also change all top-level definitions to use `let` as in F#, instead of having separate `fun` and `val` keywords.  E.g:

```
let one: int = 1

let fib (n: int): int = if n == 0 then 1 else n * fib (n-1)
```

**Comment by fenollp** [comment]
How about dropping `let` entirely for top level definitions?

**Comment by Athas** [comment]
You mean like in Haskell?  I think that requires indentation-sensitive
syntax.

-- 
\  Troels
/\ Henriksen

**Comment by fenollp** [comment]
I don't think so: Erlang's syntax is kind of like that (no `fun` keyword for named module functions) and its grammar is I believe LL(k).
I played a lot with this grammar (see [erlang-grammar](https://bitbucket.org/fenollp/erlang-grammar) and my "exotic" rework [er](https://github.com/fenollp/er)) but these were only checked with ANTLR4...

Anyway, my bet: LL(k) (and at worst LALR-1) would be able to parse this without significant spaces.
Mind pointing me to the file(s) best describing futhark's grammar? I can investigate

**Comment by Athas** [comment]
This is the parser: https://github.com/HIPERFIT/futhark/blob/master/src/Language/Futhark/Parser/Parser.y

It is a Yacc-style parser that uses `happy`.  If you install `happy` you can just run `happy -i Parser.y` to see whether any modifications you may have made causes shift/reduce conflicts.

The ambiguity arises because Futhark uses juxtaposition for function application.  For example:

```
f x = x
g y = z
```

This looks like it defines two functions `f` and `g`.  But maybe it should be read as

```
f x = x g
y = z
```

Now it defines a function and a constant.  This is the problem that is solved by requiring `let`, or by Haskell's layout rule (which basically inserts an implicit semicolon).

**Comment by fenollp** [comment]
ah then yes, you are very right. Sorry about that.

**Comment by Athas** [comment]
Actually, since you can call partial functions from constants, I don't care about circular definitions.  Use of a constant can lead to divergence anyway.  This technically makes Futhark non-strict in global constants, which is a little weird, but not the weirdest thing in the language.
