### ISSUE TITLE
Simple programs fail to run with OpenCL backend

### ISSUE THREAD

**Issue by melsman** [HIPERFIT/futhark#241]
Consider the program `bug.fut`:
````
fun main () : int =
  2 + 3
````

When compiling with `futhark-c`, the program runs fine, but with `futhark-opencl`, it does not:
`````
bash-3.2$ futhark-c bug.fut 
bash-3.2$ ./bug 
5i32
bash-3.2$ futhark-opencl bug.fut 
bash-3.2$ ./bug 
Build log:
No kernels or only kernel prototypes found when build executable.
./bug: bug.c:406: OpenCL call
  build_opencl_program(prog, device, compile_opts)
failed with error code -2 (Device not available)
bash-3.2$ ./bug -d GeForce
Build log:
No kernels or only kernel prototypes found.
./bug: bug.c:406: OpenCL call
  build_opencl_program(prog, device, compile_opts)
failed with error code -2 (Device not available)
bash-3.2$ 
````

**Comment by Athas** [comment]
Technically not a Futhark bug!  The OpenCL specification does not
require that a program be non-empty, but some drivers complain if no
kernels are required.  Intel's Beignet in particular will print a
message to stdout, and I guess Apple's OpenCL will fail completely!  How
annoying.  I used to have an early bailout to deal with such buggy
drivers, but I removed it for some reason at some point.  Guess I will
put it back.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
I have just pushed a potential fix.  Could you check whether it works?

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
If you instead add the following dummy-kernel after the typedefs, it works:

````
__kernel void dummy_kernel(__global unsigned char *dummy, int32_t n)
{
    const uint thread_gid = get_global_id(0);
    if (thread_gid >= n)
        return;
}
````

Apparently, the kernel needs a parameter (or two ;) before it works... Haven't worked hard at getting at the most simple working dummy kernel...

**Comment by Athas** [comment]
Done.  Does it work now?

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
It works:

````
bash-3.2$ cd ~/gits/tail2futhark/tests/
bash-3.2$ make testopencl
futhark-opencl -o futopencl_addd addd.fut
./futopencl_addd -d GeForce > addd.outopencl
...
-------O p e n C L --- T E S T --- R E P O R T-------
Tests succeeded:         53 /      53
Test errors:              0 /      53
-----------------------------------------------------
````
