### ISSUE TITLE
Should boolean literals be lowercase?

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#249]
In Futhark, we write boolean literals as `True` and `False`, as in Haskell.  No other keywords are capitalised.  In Haskell, this is justified by `True` and `False` being value constructors, and the language requiring value constructors to be capitalised, but I am not sure we will have that restriction in Futhark.

**Comment by Athas** [comment]
@melsman do you have an opinion on this (or on #250)?

**Comment by melsman** [comment]
Hmm - I somehow think `false`and `true` are better. An alternative is `ff`
and `tt` but those may be controversy. I can also live with `True` and
`False`... Are we going to allow for enums at some point? General ADTs as
in SML is probably out of scope, but a notion of enums could be beneficial.
Maybe enums could be provided just by having proper type abstraction,
except if we need a proper case expression...

**Comment by Athas** [comment]
I plan to eventually permit traditional sum/algebraic types, with
recursive types banned, with a conventional case-expression.  It is
clearly not good Futhark code if you go overboard with using these, but
I think a clean implementation will be simpler than trying to come up
with weird restrictions.  They will be handled entirely in the source
language.

-- 
\  Troels
/\ Henriksen
