### ISSUE TITLE
assertion error should also be issued by futhark-c

### ISSUE THREAD

**Issue by melsman** [HIPERFIT/futhark#254]
I get the following error:

    bash-3.2$ futhark-c lines_flat.fut
    futhark-c lines_flat.fut
    bash-3.2$ futhark-opencl lines_flat.fut
    futhark-opencl lines_flat.fut
    futhark-opencl: Cannot compile assertion at lines_flat.fut:52:29-52:29 inside parallel kernel.

Perhaps this error could also be issued by futhark-c...

**Comment by Athas** [comment]
It is not an error for futhark-c, as CPU code is more lenient with
regards to when you can signal errors.  If OpenCL was more flexible,
this would not be a problem (GPUs can do this just fine).

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
Hmm - yes... But then I cannot develop for GPUs by using futhark-c, which
would be good, I think... But ok... Is there any way I can use indexing
inside a map? I tried with wrapping a conditional around the indexing for
manually giving hints to Futhark about the safety, but without luck.. I
don't think I can get the program to run in parallel with futhark-opencl
without indexing... Any trick I can apply?

**Comment by Athas** [comment]
You can use indexing inside `map`s just fine.  The only question is whether the compiler is smart enough to get rid of the bounds checking.  If it can't, just prefix the expression with `unsafe`, and it will assume everything's OK.

**Comment by melsman** [comment]
Nice! Thanks for providing the `unsafe` clue...

**Comment by ahovgaard** [comment]
I agree with Martin. It would be nice if `futhark-c` at least issues a warning in all cases when `futhark-opencl` would give an error, if possible, so that one can develop for GPUs using `futhark-c`.

**Comment by Athas** [comment]
The problem is that `futhark-c` cannot possibly know how `futhark-opencl` will mangle the code, and whether it will be able to get rid of assertions and irregular allocations.  The compilation pipelines are very different.
