### ISSUE TITLE
Changing the index syntax

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#255]
In Futhark, array indexing binds tighter than application.  `f x [i]` means `f (x [i])`, not `(f x) [i]`.  I justified this by arrays much more central to Futhark than they are in other functional languages.  But as always, when introducing syntactical irregularities, problems appear.  The primary problem is that array literals are annoying to use, because they must usually be parenthesized:

```
map (!) ([true, false])
```

(Although in the particular case of SOACs, I can fix it with a grammar hack.)

However, if we change this, we might require quite a lot of lookahead to determine whether something is an application or an indexing.  The expression `f[x,y,z]` would conventionally be an application of the function `f`, but if we add just a single strategic colon - `f[x,y,z:]` - it is now a slicing of the array `f`.

Man, syntax is hard.

**Comment by henglein** [comment]
I suggest sticking to universal principles that are consistent with and
reinforce visual perception:

   - infix operators with the same argument domains (i.e. potential
   ambiguity) should be associative; visually symmetric (on a vertical) infix
   operators (such as '+', '*', '=', but not '%') should be (semantically)
   commutative;
   - wide infix operators bind less than not so wide ones; amongst equally
   wide ones, higher operators bind less.

Beyond that compromises may have to be made for convention/backward
compatibility with mathematical notation (but not so much PL notation as
that is both younger and more volatile, so not as ingrained to start with),
where this does not hold.  Using '-' for subtraction; juxtaposition for
function application; '++' for concatenation.  Although, it seems breaches
of the above conventions do manifest themselves as common problems in
practice (what is x- y+ z?).  Maybe it's time to try

Juxtaposition is tricky: it can be thought of as a zero-width infix
operator or a zero-width prefix operator or postfix operator.  General
principles suggest that it shouldn't be the latter two (what's the symmetry
breaking rule?), so it is a visual infix operator, arguably a visually
symmetric one; though, by convention, it is typically not.

In general, it appears that using general principles anchored in visual
perception with few well-reasoned, and by themselves well-reasoned
systematic, exceptions are a guideline for concrete syntax design -- and
its conveyance to users (programmers).

Fritz




On Wed, Nov 23, 2016 at 10:20 AM, Troels Henriksen <notifications@github.com

**Comment by Athas** [comment]
I have come up with a solution that feels elegant.  My proposal is to treat `a[i]` as an indexing operation exactly when there is no space between the variable name and the open bracket.  This can be easily implemented by treating `a[` as a single lexeme.  The primary downside is that it will no longer be possible to index the results of arbitrary expressions, i.e. `(f x)[i]` will always be treated as the application of `f x` to the constant array `[i]`.  I feel this is a reasonable restriction, as indexing of non-variables is rarely done in practice.  There is one frequent idiom where it occurs, which is `(shape a)[i]`, but this we can work around in the short term by binding the shape to a variable, and in the long term by making the idiom unnecessary.  (Even now, it is usually better to write it using shape annotations.)

**Comment by henglein** [comment]
This reads like a quite terrible solution.  It seems that the absence or
presence of a particular number of whitespace characters determines the
semantics of a construct (*)

Not exactly knowing what the problem is, how about reasoning something like
this as an example of retaining orthogonal syntactic reflection of a
compositional semantics:

An array can be thought of as a subtype of the/some function type with an
implicit embedding of arrays into functions; enumerations [e1,...,en]
construct arrays (I suppose this is the intended usage in the latter part
of the message); juxtaposition is function application; and mapping a
function (or maybe even any other typefunctor) is implicit.  Semantically,
then, a [e1,...,en] maps a, as a function, over the array [e1,...,en],
resulting in a corresponding array; a [e1] maps over a singleton array; and
a e1 or a(e1) for application to single elements.  Adding implicit natural
isomorphisms between singleton arrays and their element types (as well as
for any other 'freely generated' type, which is just about always
semantically safe -- their implicit application does not change their
semantics in any context), the notations a [e1] and a(e1) would be
interchangeable.  If arrays are to be kept separate from functions (to
simplify implementation of parametric polymorphic functions), then the
interface to arrays could stipulate that such can only be applied to
arrays, thus disallowing a(e) and a e as notations for application;
together with the implicit single-element array-to-element isomorphism a[e]
could be treates an element, not only an array of such elements.

Fritz

(*) Extrapolating from numerous wide-spread 'features' (ranging from
lexical subtleties, overloading and other parsing subtleties to
'practically useful' -- but then really absolutely not -- 'features' such
as null-terminated arrays and null pointers of any type), I am afraid
Futhark could contribute to additional teaching (not on solving problems,
but on lexical issues) and endless blog posts, messages, beginner errors,
etc, on the subtleties of arrays, array notation, work-arounds, syntax
extensions by preprocessors, numerous forks on Github, etc., which may be
entertaining for those writing and reading and living off of them, but
neither productive for those typing to solve real problems nor society at
large.

**Comment by melsman** [comment]
So I guess the consequence of Fritz' analysis would be to parse 'f a [e]'
as 'f a ([e])' and one would need to write 'f (a[e])' if the other
interpretation was intended.

**Comment by Athas** [comment]
That's fine.  Under my proposal, you would need to write `f a[e]` if you want `f (a[e])`.

To step back a bit, the context of the problem is as follows: If Futhark ever becomes used to some degree, it will certainly not be as anyone's primary language.  It is far too restricted (by design and intent) for that.  Instead, it will be a small language used for solving performance-critical problems within larger systems.  This creates the need for both good interoperability (purely an engineering issue), as well as a language design that does not feel too unfamiliar.  There is a tension here, because Futhark is a pure functional language (not familiar to most), and solving that tension with small syntactical concessions to the mainstream is what I'm trying to do.  In particular, I want to keep the application-by-juxtaposition notation from the lambda calculus, as I find it eases equational reasoning.

The concrete problem is then that I want to support C/Algol-style array indexing, as it is by far the most common form in wide use.

Fritz's proposal of treating arrays like functions is good, and I have considered it myself.  The problem is exactly that it requires an isomorphism between singleton arrays and scalars to work well.  This cannot be done statically - in the indexing `a is`, is the index vector `is` singleton or not? - and is much too expensive to do dynamically.  If we were building a JIT compiler, it might be viable, but alas.  Hence, I like having a syntactic (and type-wise) distinction for array indexing that strips away a dimension, possibly all of them.

One advantage of treating `a [x]` as separate from a[x]` (and arrays distinct from functions) is that there is *no case* where both would be type correct.  Hence, the type checker could easily check if the alternative would be type correct, and make the type error contain a helpful hint that perhaps that is what is intended.  No blog posts necessary!  Also, I'm not sure I have ever seen anyone write `a [x]` for indexing the array `a` in C-like language, and offhand I'm not even sure it's syntactically valid, so this issue likely will not arise much in practice.  I acknowledge that this is a lexer hack, but every other solution has worse consequences or is vastly more complicated to implement.

**Comment by henglein** [comment]
That is correct. (*) Function applications would often require using
parentheses. That is rather common in mainstream mathematics, Schönfinkel
and Curry notwithstanding.

Fritz

(*) Using juxtaposition for function application ("apply") is problematic
from a usability point of view.
Function application is nonassociative and so f g h means (f g) h, but
*not* f (g h); the required care in placing parentheses has led to $ being
introduced, with its spin-off questions
<http://stackoverflow.com/questions/940382/haskell-difference-between-dot-and-dollar-sign>
on how it relates to . and juxtaposition.  Symmetry considerations suggest
that the (invisible) apply-operator is infix, implicitly placed between its
arguments, and general considerations about infix operators suggest that
such should be semantically associative to ensure that interpreting e op f
op g as either (e op f) op g or as e op (f op g) makes no (semantic)
difference, so e1 op e2 op e3 op e4 op ... op en can be thought of as the
sequence they look like.  Function application in Schönfinkel notation (=
juxtaposition) does not satisfy that. There *is* an assocative
interpretation of juxtaposition, however, by letting juxtaposition denote
functional *composition*, so e f g denotes the composition (in conventional
order) of functions e, f and g.  Application would then require an
(implicit or explicit -- it is a natural isomorphism, so safe, but implicit
*is* problematic) isomorphism in/out between type T and 1 -> T.  So f e x
with implicit in/out, where x is not a function type (here's the problem),
then really denotes

out (f compose e compose (in x)).

Making the in/out isomorphism explicit, a suggestive notation could be
postfix-">" for in and prefix-"<" for out.  Denoting composition by
juxtaposition (note: now it is associative), this gives <f g x> for what is
written as (f . g) x in Haskell, <f >< g x> for f (g (x)) and <<f g> x> for
f g x.  Note the nonassociativity of function application is now made
visually explicit.  The fact of in/out being a natural isomorphism
motivates the use of a matching pair of symbols <, > in the concrete
syntax:  The in/out isomorphism becomes  < > = id and > < = id in concrete
syntax.  This emphasizes the semantic equality between (f . g)(x) and
f(g(x)):  It becomes

< f g x > = < f >< g x >.

Employing >< = id and observing that f id = f = id f we have

< f >< g x > = < f id g x > = < f g x >

(Recall that juxtaposition here denotes functional composition; you can
read < f g x > as either
<(f g) x> or <f (g x)> -- no semantic difference.)  The > and < should be
thought out more, though, and using juxtaposition for functional
composition shouldn't be the standard notation for composition, I believe,
but rather an abbreviation for, say, ";" (composition in diagrammatic
order) or "." (composition in conventional order).

**Comment by Athas** [comment]
I don't really buy that application by juxtaposition is a usability problem.  I find it unambiguously better than traditional application-by-parens syntax when it comes do distinguishing between multiple arguments and tuple arguments, and I don't really experience anyone being confused when they learn it (and I've taught SML and Haskell many times).  Maybe there is room for something even better, but I don't really see Futhark as a language syntax playground.  I just want something simple and fairly established so I can go crazy on compiler design instead.

I will likely go with the lexer hack.  There *is* one other radical way to do this, which I am very unlikely to do due to its alienness, but is in principle probably the best way to do it.  The idea is to treat arrays as polymorphic functions, with indexing being function application.  You can say `x i` to retrieve the element at index `i`.  However, the `i` does not have to be an integer - it can be an array of integers, in which case you get back an array of values.  That is, `x [i,j]` returns an array containing the elements at position `i` and `j` of `x`.  This nicely encapsulates slicing, e.g. if `x` has size `n`, we can take the lower half of elements by saying `x (iota (n/2))`.  With some syntax sugar for `iota`s, we can phrase this as `x (0:n)`, which is close to the `x[0:n]` that we presently support.  It would require some more compiler magic to ensure that these `iota`s are never manifested, which is why I prefer specialised syntax with guaranteed behaviour.
