### ISSUE TITLE
More concise lambda syntax

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#259]
Much against my initial wishes, Futhark seems to have turned into an ML-derived language.  In most cases, and to my surprise, I have found this preferable to the Haskell notation that I am otherwise used to.  But in some cases I am not quite so happy.  For example, our notation for anonymous functions is `fn x y z => ...`.  In Haskell, this would be written as `\x y z -> ...`.  In Java, it would be just `x y z -> ...`.

I believe that in a functional language, anonymous functions are common and their notation should therefore be concise.  It may be a little embarrassing that Java of all languages has more concise notation for lambda expressions that any functional language I know of, but unfortunately, parsing the Java notation would require infinite lookahead in a language where juxtaposition is used for function application.  However, we could improve matters a little by switching to the Haskell notation, with a leading backslash instead of the token `fn`.  This is also consistent with Futhark's emerging syntactical style, which prefers punctuation to keywords.  And it would get rid of the strange situation where both `fun` and `fn` are keywords.

Of course, maybe we don't care that much about the concision of lambda expressions.  In my Haskell code, I find that I mostly use explicit lambdas in a monadic context when imitating imperative control structures.  For pure code, I usually use currying or locally `let`-defined functions, and rarely inline lambda expressions.  But if so, I still would like to combine `fun` and `fn` into one keyword.  There is no ambiguity in Futhark.

**Comment by Athas** [comment]
One advantage of a backslash lambda is that no space is needed before the parameter name: `fn x=>x+2` versus `\x->x+2`.  (Here I also moved from a fat arrow to a skinny arrow, which I have no objective justification for.)

**Comment by Athas** [comment]
@melsman do you have an opinion on this one?

**Comment by oleks** [comment]
I suggest just going with the Haskell notation.

**Comment by melsman** [comment]
Some questions:

 - how does it look with multiple parameters and type ascriptions.
 - how does keyword highlighting work with \ ; would it be possible to
color binding occurrences different from uses?

**Comment by Athas** [comment]
It works exactly as with `fn`.  There is no grammar change, only a lexer change.  So: `\(x: t1) (y: t2) -> ...`.  It is just as straightforward to syntax-highlight as the `fn` form, and Haskell editors handle it fine.

This would also solve the ugly quirk where we have both `fun` and `fn` as keywords.  I never liked that in SML.

**Comment by Athas** [comment]
I will go with the Haskell notation, for the sole reason that it is more familiar to people.  It doesn't mesh quite nicely with the lambda return type syntax, but I have considered doing that in another way anyhow.

**Comment by melsman** [comment]
How?

**Comment by Athas** [comment]
This is the current Futhark syntax for a lambda with an ascribed return type:

```
fn x: t => ...
```

With the new syntax, it would be:

```
\x: t -> ...
```

The confusing part is that `->` might be seen as part of the return type.  This is not a problem yet, because we don't have function types (except in signatures, but that's just to the parser).  And it will probably be an extremely rare occurrence to have a lambda that returns a function.  And maybe I will just remove that return type ascription syntax entirely.  Eventually we will have named local functions, which seem a better place to define functions with verbose and complicated return types.
