### ISSUE TITLE
Implement an SML-like module system

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#260]
Martin and I have been talking about this for some time, and had a student implement the basics.  I'm now itching to finish the work and have a module system based on SML (structures, signatures, functors) in Futhark.  I will make some syntactical changes, because I find SML syntax pretty ghastly, and the first few versions will be very restricted compared to the full SML module language.  For now, this works:

```
sig SIG {
type t = (int, int)

val x: t
val f: []t -> t
}

struct STRUCT: SIG {
type t = (int,int)

val x: (int, int) = (2,2)

fun f (as: []t): t = reduce (fn (a,b) (c,d) => (a+c,b+d)) (0,0) as
}

fun main(xs: []int, ys: []int): STRUCT.t = STRUCT.f (zip xs ys)
```

Futhark will only support *opaque* signature ascription.  This will not change.  We also have only `struct` and `sig` keywords (and `functor`), rather than SMLs rather odd inclusion of both `struct` and `structure`.

Additionally, the first implementation will not support signatures with nested structures, multi-parameter functors, or fully general signature and structure expressions (e.g. no anonymous signatures or structures).

**Comment by Athas** [comment]
@melsman I just committed signature ascription support.  My solution is still pretty hacky I feel, as I didn't want to radically change the data structures used by the type checker.  We can improve it as we go along.  Do you think you can write up some nasty test cases to verify that it works?  My current signature and ascription tests are in https://github.com/HIPERFIT/futhark/tree/master/data/tests/modules

**Comment by melsman** [comment]
Well - the biggest issue is that there is no spec! ;) I would advocate that
we write up a document with typing rules (but I guess you knew that ;),
which should specify exactly how the scoping is supposed to work. It would
then become straightforward to test the spect with various examples, some
of which it seems you have already. Such a document would also serve as a
design document for how extensions can be incorporated.

BTW: did you consider adopting OCaml's 'module' keyword instead of using
'struct' and 'functor'?

**Comment by melsman** [comment]
If it is ok with you Troels, I can put something in futhark-papers...

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> BTW: did you consider adopting OCaml's 'module' keyword instead of using
> 'struct' and 'functor'?

Yes, I was going to discuss that with you.  I think I prefer OCaml's
nomenclature.  A signature would then be written 'module type', and a
functor would just be a module with some applicative syntax, right?
I.e:

    module F (A: SOME_SIGNATURE) {
      decs...
    }

Actually, when we document this stuff, we might want to avoid the term
"functor" entirely, and instead say "parametrised module" or something.
Functor is the second-most overloaded term in computer science
("strongly typed" is #1).  I know of very different things called
"functor" in at least Haskell, SML, and C++.  And of course, the
category theoretical concept, which is different again.

About the spec, sure, but I prefer playing around with things first so
we can see how well it works.  Premature specification is a waste of
time.  Especially since I want to copy SML semantics with few
exceptions, so we usually have a good intuition for what things mean.

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
I agree with your suggestions about nomenclature...

I'm writing things up quickly and use it as a working document; you are
entirely free to poke around and experiment; I can then experiment at the
semantic level...

BTW: What should the syntax be for a structure abbreviation:

  module M = MyLongModuleName

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> I agree with your suggestions about nomenclature...
>
> I'm writing things up quickly and use it as a working document; you are
> entirely free to poke around and experiment; I can then experiment at the
> semantic level...
>
> BTW: What should the syntax be for a structure abbreviation:
>
>   module M = MyLongModuleName

Yes, exactly.  And the longhand syntax for module declaration:

    module M = module { decs... }

This will wait until we have module expressions, of course.

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
Why not just

  module X = { decs... }

I also think we're better off with

  module type X = { specs }

Here is a suggestion for an extensible system:

![image](https://cloud.githubusercontent.com/assets/1167803/21615733/1a80d38e-d1df-11e6-9b6e-c2623ddf2284.png)

**Comment by Athas** [comment]
I agree with your suggestions and will modify the parser accordingly.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
I have implemented your suggested grammar in full, including signature and module expressions.  That means anonymous signatures also work; look:

```
module M: {val x: int} = {
  val x = 2
  val y = 3
}

fun main(x: int) = M.x + x
```

Not sure how useful they are, though.

But now I have only functors to go!  (And we'll need some more tests before I'm comfortable trusting all this.)

**Comment by melsman** [comment]
Cool!! Anonymous signatures are definitely useful - I use them often,
locally in modules for hiding abstract details...

Anyhow, what is the story about scoping when modules are involved. Should
the following code type check:

  val a = b
  module A = { val x = 4}
  val b = 3

Or do you only support prescoping inside a core language dec? The latter
restriction would ease the reasoning when opaque module type ascriptions
are involved...




how do you treat mutual recursion around modules? Are mo

**Comment by Athas** [comment]
No, that example is invalid.  The rule I have come up with is pretty
simple: every declaration is checked in isolation, from top to bottom,
*except* for immediately neighboring value (and function) declarations,
which are checked together.  This gives us what's important (easy
mutually recursive functions) without complicating the implementation.
If we ever add recursive data types, I'd extend this rule to also check
neighboring type definitions.  From an SML point of view, you can
pretend there is always an implicit 'and' between function definitions.

-- 
\  Troels
/\ Henriksen

**Comment by melsman** [comment]
Great! I believe that is a good restriction... I've written down a static
semantics for the language - it is pretty much straightforward; once you
support abstract types, we can do a whole lot of tests! ;)

**Comment by melsman** [comment]
Nice! I can write up a number of tests then...

ons. 4. jan. 2017 kl. 07.17 skrev Troels Henriksen <notifications@github.com

**Comment by Athas** [comment]
Just managed to get a functor application to type check for the first time:

```
module type SIG { val x: int }
module S0: SIG { val x: int = 2 }
module F0(P: SIG) { val x: int = P.x + 1 }
module S1 = F0(S0)

fun main(x: int): int = x + S1.x
```

The implementation is a little touch and go in places, but it's not completely incoherent.  Guess you *can* implement (most of) an SML module system in a week!

**Comment by Athas** [comment]
And now I managed a compile of this more elaborate example:

```
-- A functor with a signature containing an abstract type.
-- ==
-- input { [1,2,3] [4,5,6] [1f32,2f32,3f32] [4f32,5f32,6f32] }
-- output { 315 315f32 }

module type NUMERIC {
type num
val plus : num -> num -> num
val mult : num -> num -> num
val one : num
val zero : num
}

module Int {
type num = int
fun plus (x: int) (y: int): int = x + y
fun mult (x: int) (y: int): int = x * y
val one: int = 1
val zero: int = 0
}

module Float32 {
type num = f32
fun plus (x: f32) (y: f32): f32 = x + y
fun mult (x: f32) (y: f32): f32 = x * y
val one: f32 = 1f32
val zero: f32 = 0f32
}

module DotProd(T: NUMERIC) {
fun dotprod (xs: [n]T.num) (ys: [n]T.num): T.num =
  reduce T.mult T.one (map T.plus xs ys)
}

module IntDotProd = DotProd(Int)
module Float32DotProd = DotProd(Float32)

fun main(xs: [n]int, ys: [n]int,
         as: [m]f32, bs: [n]f32): (int, f32) =
  (IntDotProd.dotprod xs ys,
   Float32DotProd.dotprod as bs)
```

This is more or less exactly the kind of code I want in the upcoming Futhark standard library.

I found some parts of the implementation pretty ugly.  In particular, the substitution to make `IntDotProd.num` equal to `int` was very weird to implement - possibly because the type checker does not have any kind of "type equality environment", so equality of types is by equality of realised type names, which means I need to do all kinds of substitutions to get the right names where I expect them.

**Comment by Athas** [comment]
This also means our type errors are horrible, and use a mix of external and internal names.  Clearly some work to be done.  But we can at least start working on Futhark libraries now.

**Comment by Athas** [comment]
Is something like this supposed to be permitted?

```
module F(P:{type t val f:t->t}): {type t = P.t val f2:t->t} = {
type t = P.t
fun f2(x: t): t = P.f (P.f x)
}
```

**Comment by Athas** [comment]
Looks like it works in SML.

**Comment by Athas** [comment]
Now it works in Futhark, too.

**Comment by Athas** [comment]
So, @melsman, when do you think we can close this issue?  There are things we will definitely want to add - `open` declarations, signature inclusion, probably `where` clauses - but I think the current module system works, so those should be issues on their own.  Maybe a few more tests?

**Comment by melsman** [comment]
How are tests run nowadays? The futhark/README.md file suggests to run
`data/runtests.sh` but I can find no such script in the data directory...

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> How are tests run nowadays? The futhark/README.md file suggests to run
> `data/runtests.sh` but I can find no such script in the data directory...

`futhark-test data`

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
Any preferences on whether we should go with SML-style `where` or OCam-style `with` for signature constraints?

**Comment by melsman** [comment]
You choose.. I think the syntax should be at mty-level:

  mty ::= { spec } | mtid | mty where module longmid = longmid
           | mty where type longtid = ty

It is an open question in what scope we should type check ty in module
types of the form

       mty where type longtid = ty

If we choose to include the environment provided by mty in the scope,
"where type" constraints can be used instead of "sharing" specification
constraints...

**Comment by Athas** [comment]
Isn't it more elegant to check in the context of mty, then?

**Comment by melsman** [comment]
Yes but there are cases where the content of mty would shadow over
identifiers one would want to refer to...

    module F (X : { type t }) : { module X : {} type t } where type t = X.t

Looking at the above, we need a nicer syntax than "where type":

    module F (X : { type t }) : { module X : {} type t } with t = X.t

We can use "with" instead of "where type" and "with module" instead of
"where module". We don't need "with module" constraints to start with...


On Sat, Jan 14, 2017 at 12:10 PM, Troels Henriksen <notifications@github.com

**Comment by melsman** [comment]
module type T = { type t }
module F(X:T) : T with t = X.t = { type t = X.t }

**Comment by Athas** [comment]
I don't see how your syntax resolves the shadowing problem.  (But it can be resolved by renaming the outer type.)

I agree that the `type` keyword should not be necessary when adding type constraints.

Will we use `and` to combine several constraints or do you have a better idea?

**Comment by Athas** [comment]
We now have `open`.

**Comment by Athas** [comment]
I added some basic documentation to http://futhark.readthedocs.io/en/latest/language-reference.html#module-system
