### ISSUE TITLE
Type abstraction issue

### ISSUE THREAD

**Issue by melsman** [HIPERFIT/futhark#262]
The following code should not type check:

    module type S = { type t val a : t val f : t -> int }
    module B : S = { type t = int val a:t = 3 fun f (a:t):t = a }
    module C : S = B
    fun main() : int = C.f B.a

Here is a log:

    bash-3.2$ futhark-c -V 
    Futhark 0.1
    (C) HIPERFIT research centre
    Department of Computer Science, University of Copenhagen (DIKU)
    bash-3.2$ futhark-c abs.fut
    bash-3.2$ ./abs 
    3i32
    bash-3.2$

**Comment by Athas** [comment]
Can you elaborate on what is expected here?  Should we really create fresh names whenever we match a module opaquely?  I thought signature ascription was only about narrowing.

**Comment by melsman** [comment]
If we're interpreting ':' as SML's ':>' then signature ascription results in the abstracted environment and not the transparent environment. Here is what happens in mosml:

    Moscow ML version 2.10
    Enter `quit();' to quit.
    - signature A = sig type t val a : t val f : t -> int end;
    > signature A = /\t.{type t = t, val a : t, val f : t -> int}
    - structure A :> A = struct type t = int val a = 5 fun f a = a end;
    > New type names: t
      structure A : {type t = t, val a : t, val f : t -> int}
    - structure B :> A = A;
    > New type names: t/1
      structure B : {type t = t/1, val a : t/1, val f : t/1 -> int}
    - B.f A.a;
    ! Toplevel input:
    ! B.f A.a;
    !     ^^^
    ! Type clash: expression of type
    !   t
    ! cannot have type
    !   t/1
    -

**Comment by Athas** [comment]
Annoying.  This will require us to generate new type names, and not just hide right-hand sides of type definitions.  I'm not sure I like that.  Is it necessary for soundness?

**Comment by melsman** [comment]
If one is to understand a module by solely looking at a signature, we want
this semantics, I believe. There is no issue with soundness as we could
also choose to expose only the transparent environment, which would still
be sound. I don't really like the mix between the transparent and the
opaque view as I can't really understand the model without understanding
the implementation...

**Comment by Athas** [comment]
All right, I will implement this semantics.
