### ISSUE TITLE
Design a standard library

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#267]
With the introduction of a module system, we are now ready to think about providing a standard library so every Futhark program does not have to reinvent the same old primitives.  I have added code to the compiler such that the Futhark files in [this directory](https://github.com/HIPERFIT/futhark/tree/master/futlib) are automatically made available to every program being compiled.  For examples, `import futlib.sandbox` would cause the inclusion of [this file](https://github.com/HIPERFIT/futhark/blob/master/futlib/sandbox.fut).  This is done by the Futhark compiler embedding the file contents at compile time.  Thus, the user need not worry about include paths or the like.

Our file inclusion mechanism will need some work.  Currently, `include` works more or less exactly like C header files, which means the order of inclusion matters, as type checking is done post inclusion.  This will be fixed.

A deeper problem is what facilities the standard library should even support.  What are the base abstractions?  Which signatures should be defined?  For example, I want to define a signature for comparable types:

```
module type ORD {
type t
val eq: t -> t -> bool
val lt: t -> t -> bool
val gt: t -> t -> bool
}
```

This allows me to define a functor:

```
module Ordering(T: ORD) {
fun max (x: T.t) (y: T.t): T.t =
  if T.gt x y then x else y

fun min (x: T.t) (y: T.t): T.t =
  if T.gt x y then y else x

fun max_elem (x: T.t) (xs: [n]T.t): T.t =
  reduce max x xs

fun min_elem (x: T.t) (xs: [n]T.t): T.t =
  reduce min x xs
}
```

Note that `max_elem` and `min_elem` require me to pass in a neutral element.  This could also be part of the signature (turning `ORD` into the signature for lattices), I guess, but is it really natural to define negative and positive infinity as the neutral elements for `max_elem` and `min_elem` on floating point numbers?

There are a lot of design questions to answer.  Fortunately, we can just try out a bunch of things and see what works well.  Maybe some student projects are lurking somewhere in this space.

**Comment by Athas** [comment]
@nqpz volunteered to help write a Futhark coding style document so we can nib the mess in the bud.

**Comment by Athas** [comment]
So, what about module names?  Do we keep them capitalised as in SML or Haskell?  Or lowercase as in Rust and other nice languages?  One advantage to lowercase names is that you can write modules whose name are the same as some type.  This lets us write things like `f32.sqrt` instead of `F32.sqrt`.

We don't need to worry about name clashes, because terms, modules, and module types are all in their own namespaces anyway.

**Comment by melsman** [comment]
A possible design would be to allow small-capitalised modules names for
types and capitalised modules names for non-types? A possibility is also to
have a "type t" in each module that has a natural inhabitant. Let's
discuss...

**Comment by Athas** [comment]
Only for built-in types, or also for user-defined types (e.g. complex
numbers)?  And when is a module a "type module"?


-- 
\  Troels
/\ Henriksen
