### ISSUE TITLE
Internalise lookupTypeVar error

### ISSUE THREAD

**Issue by melsman** [HIPERFIT/futhark#269]
The following program fails to type check:

    module F (X : { type t type s }) : { type t = X.s type s = X.t } =
     { type t = X.s type s = X.t }
    module A = { type t = f32 type s = i32 }
    module B = F(A)
    module C = F(B)
    fun main() : int = 3

Here is what `futhark-c` says:

    futhark-c: Internalise.lookupTypeVar: Type 's_35' not found

**Comment by Athas** [comment]
This was a fun one with a simple (and in retrospect, obvious) fix.  Are you also collecting tricky examples that happen to already work?  That's important to prevent regressions when/if we clean up the implementation in the future.

**Comment by melsman** [comment]
Should I just commit to data/tests/modules/ ?

lør. 7. jan. 2017 kl. 17.28 skrev Troels Henriksen <notifications@github.com

**Comment by Athas** [comment]
Martin Elsman <notifications@github.com> writes:

> Should I just commit to data/tests/modules/ ?

I just renamed that directory to tests/modules, but yes.  Don't worry
about file naming schemes or any of that; I'm hardly consistent myself -
just put a comment at the top hinting at what you're testing.

-- 
\  Troels
/\ Henriksen
