### ISSUE TITLE
Make --version great again!

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#270]
I seem to recall that once `futhark --version` showed a hash for the git commit that was used to build that version.

I was just running an example on my own machine and the GPUs in the clusters, and found different results. I wanted to verify we where using the same version of the compiler, but all the information I can find is that we're using version `0.1` :cry:

**Comment by Athas** [comment]
You are very welcome to add it back.  The problem I had was that my
Setup.hs hack broke 'cabal sdist'.  But maybe we don't care about that.
(It's 'stack sdist' anyway now.)


-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
Fixed in 8791fd45409de0219097fea46a14f620694cffae.
