### ISSUE TITLE
Should we ban recursive functions from Futhark?

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#273]
Recursive functions are a bad idea in Futhark.  There are two reasons for this:

1. The Futhark compiler does not perform tail-call optimisation.
2. It is not _possible_ to efficiently implement non-tail call recursion on GPUs, because threads have essentially no stack.

Issue **2** is only a problem for the part of the code that runs on GPUs, but when writing a function, you cannot know where it will eventually run, and I'm not terribly interested in making parallelisability part of the function type.  Issue **2** *could* be solved via general flattening, which *can* handle arbitrary recursion (but not efficiently).  But until we come up with some solution, it may be better to be more honest about what kind of code the language expects you to write.

Banning recursion is not as devastating as it might seem, as Futhark has other looping constructs.  In particular, our `do` loops can be seen exactly as tail-recursive functions with some syntax sugar.  None of our current benchmarks use recursive functions, and the only tests that do are those that explicitly test recursion.

Of course, Futhark is not a "GPU language" - it is a high-level parallel language - and we might conceivably want to run on parallel platforms where recursion is fine, like multicore CPUs.  Restricting the language due to technical quirks of one major platform could be seen as a layering violation.  Of course, if we ever want to translate to something like FPGAs, recursion is right out as well.

I am currently slightly in favour of banning recursive functions.  This is partially due to my general preference for small languages, and partially due to my belief that recursion is a kind of low level building block, the functional equivalent of ``go to``, that we may not need in idiomatic array code.

A variation, which I am also seriously considering, is to only permit recursion in the case of *tail* recursion.  This would solve our problems, and still permit the writing of e.g. state machines using recursive functions (as is most natural).

**Comment by Athas** [comment]
Right now, if you are unlucky enough to compile a Futhark program that ends up with a recursive function inside of a parallel kernel, you will get a cryptic compiler error from somewhere near the code generator.

**Comment by oleks** [comment]
On Wed, Jan 11, 2017 at 5:14 PM, Troels Henriksen <notifications@github.com>
wrote:

> Right now, if you are unlucky enough to compile a Futhark program that
> ends up with a recursive function inside of a parallel kernel, you will get
> a cryptic compiler error from somewhere near the code generator.
>
I think instead, someone(tm) should fix that, and point 1.

Let Futhark _attempt_ to unfold a recursive function into an efficient
kernel, and let the user know nicely if it fails to do so. The whole point,
as I see Futhark today, is to make GPU programming easier and better
through a more (limited) functional approach. I think removing recursion
works against that. It almost turns Futhark into a SQL of sorts.

-- 
Oleks

**Comment by Athas** [comment]
What would you tell the programmer?  The error is detected on a highly
transformed program that may bear very little similarity with what the
programmer wrote.  The recursive call may be hidden inside a library
function.

The nice thing about tail-recursive functions is that we can _always_
compile them.  General recursion can only be compiled by throwing them
at some huge black box (from the POV of the programmer) and hoping for
the best.

I am a big fan of solving problems by removing features.

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Wed, Jan 11, 2017 at 5:31 PM, Troels Henriksen
<notifications@github.com> wrote:
> What would you tell the programmer? The error is detected on a highly
> transformed program that may bear very little similarity with what the
> programmer wrote. The recursive call may be hidden inside a library
> function.
>
> The nice thing about tail-recursive functions is that we can _always_
> compile them. General recursion can only be compiled by throwing them
> at some huge black box (from the POV of the programmer) and hoping for
> the best.
>
> I am a big fan of solving problems by removing features.

There is also the possible argument that not *all* of what is
considered "functional programming" is good for the programmer. Among
other things, removing general recursion would greatly simplify termination
analysis; Hurray!

**Comment by Athas** [comment]
Futhark has while loops, so it would not affect termination analysis.

-- 
\  Troels
/\ Henriksen

**Comment by oleks** [comment]
On Wed, Jan 11, 2017 at 6:22 PM, Troels Henriksen <notifications@github.com>
wrote:

> Futhark has while loops, so it would not affect termination analysis.


That depends on the while-condition ;-)

**Comment by fenollp** [comment]
As long as there's `map` & `fold` or similar... I say remove the feature!

**Comment by Athas** [comment]
I have decided to do this.  The mechanism will be by changing the type checker to require that a function (or constant) must be defined before it is used, and a function will not be in scope of itself.  This will require some changes to test and benchmark programs.

In the future, we will loosen this restriction.  Mutually tail-recursive functions would be useful for encoding state machines.  But for now, we don't have the manpower to support this properly, so we might as well ban it and spare programmers some uncomfortable surprises.

**Comment by jarble** [comment]
@athas It might be possible to implement tail-recursion using while-loops in Futhark.

Since Futhark doesn't have recursion yet, this function won't compile:

```
let rec fibhelper(x: i32, y: i32, n: i32): i32 =
  if n == 1 then x else fibhelper(y, x+y, n-1)
```

But it could be rewritten using a while-loop, simulating recursion by reassigning the function's parameters with each iteration of the loop:
```
let fibhelper(x: i32, y: i32, n: i32): i32 = let (x,y,n,continue,result) = loop (x,y,n,true,0) while continue do
  if n == 1 then (x,y,n,false,x) else (y, x+y, n-1,true,result) in result

```
Would it be possible for the Futhark compiler to implement tail-recursion in this way?

**Comment by athas** [comment]
Yes, you can do that, and that's the recommended workaround.  The reason we do not support it directly in the language is because it's actually not that easy to define what "tail call" means.  Is the following function tail recursive?

```
let rec fibhelper(x: i32, y: i32, n: i32): i32 =
  if n == 1 then x else (y, x+y, n-1) |> fibhelper
```

Until we have good answers (or more likely, good compilation of recursive parallel functions), we will not support recursive functions.

**Comment by jarble** [comment]
In languages that don't support recursion, it is possible to eliminate recursion [using macro expansion](https://stackoverflow.com/a/77470186/975097) if the maximum depth of recursion is known at compile time.
