### ISSUE TITLE
Should we drop support for LTS 1.15 (GHC 7.8)

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#275]
Futhark presently builds on three different versions of GHC.  Most notably, it builds on GHC 7.8, which is from before Applicative was made a superclass of Monad (and some other Prelude reorganisation took place).  By default, Futhark builds with GHC 8.  I suspect Travis is the only place non-GHC 8 builds take place.  It is very easy to accidentally write code that does not work with GHC 7.8, and it seems like a pointless burden to have to go back and add the missing imports and such.

Should we just ditch the GHC 7.8 support?  It was put in place at a time where Futhark was unable to build on GHC 8 (due to GHC bugs).

**Comment by RasmusWL** [comment]
Yes, let's ditch it. :boom:

For me it seems like it is just annoying work, that ultimately doesn't give us any benefits.
