### ISSUE TITLE
Add support for user-defined infix operators

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#280]
It's pretty tiresome to implement number-like types without being able to use infix operators, so that will have to change.  An OCaml/F#-style system would be easy to implement.  In this system, infix operators are a distinct lexical category, just like Haskell.  Unlike Haskell, the precedence and fixity of any operator is a function of the leading characters in the operator.  User-defined operator precedence is *not* permitted, and the grammar remains context-free.

In OCaml and F#, the precedence of an operator is given by the first symbol, with correspondences to the usual mathematical precedences: e.g., `+^` has the same precedence and fixity as `+`, while `*^` has works like `*`.  This can be a little ugly, but is *much* easier to read.  I base this on many years of Haskell where I have had to guess at operator priorities, and usually just added parentheses everywhere.

In Futhark, I suggest we twist this design a little, by permitting the precedence to depend on *several* characters.  This is to keep our current (and conventional) operator priorities, where e.g. `>>` (bitshift) binds more tightly than `>`.  In Futhark, the precedence of an operator is the same as longest prefix of the operator that corresponds to a "default" operator.  Hence, `>>^` binds as `>>` and `>^` binds as `>`.

I also suggest that the short-circuiting `&&` and `||` operators will not be definable, since the overloaded variants would not be short-circuiting.

I'm open to suggestions on a different design, but given how simple I think the above would be to implement, I'll probably do it soon.

**Comment by melsman** [comment]
For this to be really useful, I presume we need an open construct in the
modules language...

**Comment by Athas** [comment]
Sure, but that's an orthogonal issue.
