### ISSUE TITLE
SplitSpace simplification results in futhark-opencl error (Cannot allocate memory in kernel.)

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#282]
When turning on both my new segmented redomap, and inlining SplitSpace, some of my test programs result in errors when compiled with `futhark-opencl`

`segsum-comm.fut` and `real-nocomm.fut` both work fine, but there are problems with for example `ex1-comm.fut` and `ex1-nocomm.fut`. So it seems like there is only problems when there is output from the "map part" not only used by the reduce.

Error reported is `Cannot allocate memory in kernel.`

**Comment by Athas** [comment]
Rasmus Wriedt Larsen <notifications@github.com> writes:

> When turning on both my new segmented redomap, and inlining
> SplitSpace, some of my test programs result in errors when compiled
> with `futhark-opencl`
>
> `segsum-comm.fut` and `real-nocomm.fut` both work fine, but there are
> problems with for example `ex1-comm.fut` and `ex1-nocomm.fut`. So it
> seems like there is only problems when there is output from the "map
> part" not only used by the reduce.
>
> Error reported is `Cannot allocate memory in kernel.`

Yes, that is why I sent you an email that we were going to do something
else.  That simplification rule is going anyway.  Continue using
SplitSpace, but do not use SplitArray.

-- 
\  Troels
/\ Henriksen
