### ISSUE TITLE
Improving file inclusion

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#289]
Futhark currently has a fairly crude file inclusion system that is pretty reminent of C's `#include`.  It also runs before type-checking, and the type checker is just given a concatenated program.  This is not really acceptable, and has all kinds of weird side-effects where inclusion order matters.

Today, Cosmin, Martin and I discussed what we should do instead.  We want a simple system that permits easy calculation of a dependency graph between files (and that graph must actually be a DAG).  We decided on a system where a source file must declare up front (before any other declarations) which other files it will reference, using the `import` keyword:

```
import "foo"
import "bar/baz"
```

The above will bring names declared in the files `foo.fut` and `bar/baz.fut` into scope for the rest of the file.  The `.fut` extension is implied.  The use of string syntax is to permit file names that are not valid in Futhark identifiers.  But maybe that is not necessary?  Qualified imports are also possible:

```
import "foo" as Foo
import "bar/baz" as Quux
```

This will create two modules, `Foo` and `Quux`, that contain whatever is in the referenced files.  How exactly the file names map to file system defiles is determined by the compiler search path, as is common.

One important property about this system is that we can determine early, and before type checking, exactly which files we will need to read, and then perform all file I/O up front.  This prevents the type checker from needing the ability to read files.

I'd like some final feedback and sanity-checking on this design (and I'll do my own due diligence by comparing with Rust, which is generally seen as one of the best designed languages these days).

**Comment by RasmusWL** [comment]
Why the slash instead of dot? (I mean why `import "bar/baz"` over `import "bar.baz"`?)

And the quotes seems unnecessary, is it really that bad modifying the parse? :D

**Comment by Athas** [comment]
You can have dots in a file name if you want.

And it would be really bad having context-sensitive lexing.

**Comment by Athas** [comment]
The above design has two issues:

One is a general problem with SML modules.  When you use `open` to bring the names in some module into scope, you are also making them available inside the *current* module.  Example:

```
module A = { val a = 2 }
module B = {
  open A
  val b = a + 2
}
```

Now you can say `B.a` and get the value 2.  I don't like this much, because it means that if you just want to open some other module to ease the notational overhead in the implementation of your module, it becomes part of your public interface.  This problem doesn't occur if you use a module type ascription, where you explicitly state which names should be visible.  In the above example, we would ascribe `B` with the module type `{val b: int}`, which would hide `a`.  However, with the above design, if you use `open` in a *file*, you are out of luck, because when that file is imported, it's not (necessarily) going to be matched to a module type.

Personally, I find it a little awkward that `open` also adds the opened names to the module being defined.  One solution is to change `open` to only modify the current (local) scope, and add an `include` keyword that behaves like the old `open`.  That's what `include` does for module types anyway.

The second problem with the above design is that it does not by itself provide *abstraction*.  As the implicit module defined by a file has no associated module type, *everything* is visible (although internal modules may of course contain abstract types).  The problem here is that module types are the only method of abstraction we have.

The only conclusion I can see is that we have no choice but to support module types at the file level, just like how SML has its `.sig` files.  I guess they would be called `.futi`?  I just have an instinctive dislike of spreading them up like this.  If anyone can come up with a nice syntax for letting a `.fut` file start with a module type expression describing its contents, that would be preferable.  Then we can keep the old semantics of `open`, too.

**Comment by Athas** [comment]
We will need to rethink qualified imports, as I have decided we don't want `as` to be a keyword.  It's too commonly used as a variable name.  Maybe we can go back to an idea for full integration with the module system that we initially ditched, and use the module system for naming:

```
open import "foo/bar"
```

versus

```
module M = import "foo/bar"
```

We could require that such import-modules may appear only at the beginning of the file, or relax it a bit and permit at any top-level position.  This would permit intermixing of file inclusion and module declarations, which may sometimes be useful:

```
module FancyLinAlg = LinAlgFunctor(include "martinlib/fancy_vector_space")
```

But maybe we're getting too fancy now.  The reasoning behind the restrictions is to make it easier to find out which other files are referenced by some source file, so we can find a compilation order with no cycles.

**Comment by melsman** [comment]
How about "import path in mid"? Otherwise, "module mid = import path" could
work, I guess...

søn. 29. jan. 2017 kl. 12.07 skrev Troels Henriksen <
notifications@github.com>:

**Comment by Athas** [comment]
I like "import path in mid".  But are we completely certain we will
never want a closer integration between files and modules?  We don't
have to do it right now, but we can leave the syntax open for future
extension.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
Another advantage of integrating it with the module system is that it means we can re-use the same mechanisms and rules for shadowing and duplicates.  So, here is what I will implement:

There will be a new strexp:

```
strexp ::= ... | 'include' filename
```

Module expressions using this strexp will probably only be type-correct at the top-level, we'll see.

As a (parser) shortcut, the form

```
include filename
```

will be permitted at top-level as a shortcut for

```
open include filename
```

(Although I guess that means `open` will have to take a *strexp* as argument, not a name...)

In the future, we will need signature files.  For now, I will not change the behaviour of `open`.

**Comment by melsman** [comment]
I don't think it makes sense to have "open include path" - but we can have
"include path" at toplevel mean "local module X = include path in open X
end"...

søn. 29. jan. 2017 kl. 16.11 skrev Troels Henriksen <
notifications@github.com>:

**Comment by Athas** [comment]
Unfortunately, we don't have `local`.

**Comment by Athas** [comment]
More generally, what is the justification for `open` only accepting names?  Is something wrong with e.g. `open F(X)`, that is, opening the result of a functor application?

**Comment by Athas** [comment]
Implementation-wise, the AST will support `open include path`, but we can limit it in the parser if you see a problem.

**Comment by Athas** [comment]
(Also, some of those `include`s up there should be `import` instead.)
