### ISSUE TITLE
KernelThread only active if `localid < k1 && globalid < k2`

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#299]
I am working on performing segmented reductions when the segment size is small, by loading the data from multiple segments into one group and performing a segmented scan by `GroupScan`. So far so good.

I have taken the approach that I will load data from a segment if I can fit the *whole* segment into a group. So if the segmentsize is 3, and the groupsize is 8, we will only fit 2 segments per group. The last group might contain fewer segments that the other, if for example we have 3 segments of size 3, using groupsize of 8, the first group will have 2 segments and the second group will only have 1 segment.

I am looking for a way to restrict the threadspace such that threads will only be active if `localid < k1 && globalid < k2` for some constants `k1` and `k2`.

I thought this was the purpose of `NestedThreadSpace`, but the code it generates only uses the global-dim-size to determine if a thread is active or not. Is this a bug? or how is `NestedThreadSpace` supposed to be used?

---

Using this scheme of performing segmented redomap, an other issues I have is how to handle `KernelInput` that are invariant to the inner redomap, but are defined by some of the "outer" maps. But maybe I can tackle that at some other point.

---

I made a huge table for the example where segment_size = 3, num_segments = 3. group_size = 8. I don't know why, but here it is.

```
| globalid | localid | segment_index | active (y/n) |
|----------|---------|---------------|--------------|
|        0 |       0 |             0 |            y | 
|        1 |       1 |             0 |            y | 
|        2 |       2 |             0 |            y | 
|        3 |       3 |             1 |            y | 
|        4 |       4 |             1 |            y | 
|        5 |       5 |             1 |            y | 
|        6 |       6 |             - |            n | 
|        7 |       7 |             - |            n | 
|          |         |               |              | 
|        8 |       0 |             2 |            y | 
|        9 |       1 |             2 |            y | 
|       10 |       2 |             2 |            y | 
|       11 |       3 |             - |            n | 
|       12 |       4 |             - |            n | 
|       13 |       5 |             - |            n | 
|       14 |       6 |             - |            n | 
|       15 |       7 |             - |            n | 
```

**Comment by Athas** [comment]
No, NestedThreadSpace is used when you want a very specific topology of the local thread space.  In particular, the passed-in total group size must equal the product of all the semantic group sizes in the NestedThreadSpace structure.  You don't need this - it's used for doing tricky tiling tricks.

In your case, why don't you just use `If` statements to stop some threads from running the code you want to protect?  Note that the `GroupScan` *must* be at the top level: every thread must enter it, or you will get a deadlock.  (If you can guarantee that every thread in the group goes the same way in a branch, that's fine too, and we actually depend on this for some particularly tricky cases of tiling.)

The entire notion of a thread being "active" is a bit of a hack.  If you can come up with something more elegant, please do.

**Comment by RasmusWL** [comment]
Yes I can just use an `If` statement, and that was my current plan. I just wanted to see if the current infrastructure supported my case out of the box. The code I want to protect is indexing the input array to read an element -- is there a function in the compiler to get a dummy value of a specific type? (not that it is hard to create, but no reason to duplicate the code)

**Comment by Athas** [comment]
Yes, there is `blankPrimValue` and `Scratch`.

**Comment by coancea** [comment]
I think you can protect the whole body (the map part) inside the if,
except for the computation of the local/global thread id in the begining.

However, for the intra-block segmented scan/reduce part you will need to 
utilize all
threads (and initialize the "iddle-thread" elements with the neutral 
element)
otherwise the barrier assumed will wait forever.

**Comment by RasmusWL** [comment]
I did solve this problem by just using an `If`, so I'll go ahead an close it!
