### ISSUE TITLE
Which Python?

### ISSUE THREAD

**Issue by cathalgarvey** [HIPERFIT/futhark#302]
Stupid question, sorry. With the Python and PyOpenCL backends, does Futhark emit Python 2 or Python 3 code, or a compatible intermediate form?

**Comment by Athas** [comment]
The intent is that it's compatible with both, but in practice I wouldn't be surprised if all our testing systems ran Python 2, and hence it has some breakage on Python 3.

**Comment by Athas** [comment]
A quick check suggests that Python 3 works fine.

**Comment by cathalgarvey** [comment]
Fantastic, thank you!

I know I could have made a few spot-checks, but on their own they 
wouldn't answer the question per-se, because any script *might* run in 
both. But it's good to know that 3 is a targeted platform, *and* that 
it seems to work. :)

--
@onetruecathal / @cathal@quitter.is
