### ISSUE TITLE
Incorrect "Unused variable" error with map

### ISSUE THREAD

**Issue by nqpz** [HIPERFIT/futhark#305]
When I run `futhark -s` on
```
fun main () : []i32 =
  let x = 0
  let xs = map (+ x) [1]
  in xs
```
it prints
```
Unused variable 'x'.
```
even though it is used.

**Comment by nqpz** [comment]
This is with the newest futhark from git.

**Comment by Athas** [comment]
Yeah, the unused-variable stuff is a total hack.  There's also some false positives around.  I can fix it, but we might want to think about how to automatically test it eventually.
