### ISSUE TITLE
Allow choosing GPU device by ID

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#315]
On many of our machines there are two identical GPUs. Currently we can only select devices by name (or platform), which is no good because they have the same name :)

**Comment by RasmusWL** [comment]
I just tried this out on on our TITAN machine, and it did not work. Passing `-d 'GTX'` did work, but `-d '#0 GTX'` or `-d '#1 GTX'` did not.

```
./f32-reduce-nocomm.vanilla.bin: /usr/local/cuda-8.0/targets/x86_64-linux/lib/libOpenCL.so.1: no version information available (required by ./f32-reduce-nocomm.vanilla.bin)
./f32-reduce-nocomm.vanilla.bin: Could not find acceptable OpenCL device.
```

**Comment by Athas** [comment]
There is no GTX device on the TITAN machine.
