### ISSUE TITLE
Add parametric polymorphism

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#324]
Full parametric polymorphism for functions and data types would be nice.  Only rank-1 polymorphism will be supported (i.e. the type quantifier must be outermost).  I'm not sure about the syntax, though.  In ML we have:

```
type 'a foo = []'a
```

But I've never liked putting the type variables in front of the type name.  To me, a parametric type is a type function, so it should look like a function definition.  The apostrophes before type variables may be necessary, though.  Maybe something like:

```
type foo 'a = []'a
```

Now, what if we have two type variables?  Should it be

```
type foo ('a, 'b) = []'(a, 'b)
```

or

```
type foo 'a 'b = []('a, 'b)
```

Actually, for type abbreviations, we don't need the apostrophes at all:

```
type foo a b = [](a,b)
```

But it's necessary when using parametric polymorphism in functions:

```
fun id (x: a) = x
```

Is `a` a polymorphic type, or the name of a defined type `a`?  We could solve this by always requiring explicit quantification of type variables:

```
fun id 'a (x: a) = x
```

Here, the apostrophe is necessary for doing the quantification, but not when referring to the variable.  How would this look like in a module type spec?

```
val id `a: a -> a
```

I guess that's not so bad.  I could live with that.  PureScript requires all type variables to be explicitly quantified (with a `forall` keyword), so we're not in completely uncharted territory here.  And of course, once we get type inference, we might not need to mention the type variables at all in most cases.

**Comment by Athas** [comment]
I am probably going to go with this notation for functions and type definitions:

```
type foo 'a 'b = [](a,b)
```

```
fun id 'a 'b (x: a) (y: b) = (x,y)
```

```
val id 'a 'b: a -> b -> (a,b)
```

**Comment by melsman** [comment]
... I thought we didn't have "fun" anymore ;)

**Comment by melsman** [comment]
hmm; I think we need consistency with specs in module types. Here it looks
ugly with the notation:

  val f 'a : a -> a

I like better the notation:

  val 'a f : a -> a

which would be consistent with a prefix notation for bindings as well:

  let 'a id (x:a) : a = x

An alternative would be to move the binding inside the type:

  val f : 'a.a -> a

which could later be extended:

  val apply : 'b.('a.a->a) -> b -> b

Moving the binding inside the type, however, makes it impossible to refer
to the type variable within a function being defined...

**Comment by Athas** [comment]
Putting type variables before the name would work poorly for type definitions.  I'd prefer the postfix notation of Haskell, not the prefix notation of ML (although it's not a huge loss if we can't make it work).

Why do you think `val f 'a : a -> a` is ugly?  I agree I'm not used to it, but I'm not sure it's that bad.

I could also live with the simple version of the last notation you suggest:

```
 val f : 'a.a -> a
```

The extended version involves rank-2 types, right?  I'm not sure we have any idea how they would work in Futhark.

**Comment by melsman** [comment]
I think what you suggest is ok. We could allow for a derived form:

  val f : 'a.a->a

to mean

  val f 'a : a -> a

as you somehow suggest...

Yes - for now, we don't need rank-2 types...

fre. 31. mar. 2017 kl. 11.26 skrev Troels Henriksen <
notifications@github.com>:

**Comment by Athas** [comment]
I like putting the type quantifiers to the left of the colon, because it emphasises that they can appear only at the top level.  You're right that it makes little sense from a purely type-theoretical viewpoint.

**Comment by Athas** [comment]
I want to create some form of consistency between type variables and shape declarations (issue #327), and it's causing some issues.  Right now, we can write

```
fun vecadd (x: [n]i32) (y: [n]i32) = map (+) x y
```

It is implicit that `n` is bound here.  This can be seen as syntactic sugar for:

```
fun vecadd #n (x: [n]i32) (y: [n]i32) = map (+) x y
```

Now the binding of `n` is explicit.

With our proposed design for type variables, they must *always* be explicitly bound.  This is not allowed:

```
fun id (x: t) = x
```

(Except, of course, if `t` is a known type.)  Instead we write:

```
fun id 't (x: t) = x
```

The reason is that we do not (syntactically) distinguish a reference to a type variable from a type name, the way ML does.  If you make a typo in a type name, then instead of an error that some type does not exist, you would end up writing a polymorphic function instead.  I also don't really like the fact that some parameters are implicitly bound, and others are not:

```
fun array_id 't (x: [n]t) = x
```


One solution is to just require the apostrophe on type variable references, too:

```
fun id (x: 't) = x
```

Then everything can be implicit.  We can still permit the explicit syntax if people want it, but it will not be required.

**Comment by Athas** [comment]
Alternatively, we could also require all sizes to be explicitly bound.  I think this was @coancea's original design, but I find it a little clumsy by our current standards:

```
let matmult #n #m #p (x: [n][m]i32) (y: [m][p]i32): [n][p]i32 = ...
```

versus just

```
let matmult (x: [n][m]i32) (y: [m][p]i32): [n][p]i32 = ...
```

Maybe it's a better design, though.  It also solves an annoying wart, which is the behaviour when you have a typo in a shape name that is supposed to refer to a variable in scope:

```
val somesize = 4
fun f (x: [somesizee]i32) = ...
```

I made a typo in the shape declaration, but I won't get an error, it'll just bind the name `somesizee` instead.

**Comment by Athas** [comment]
Here's an idea: if you want to implicitly bind something (whether a type parameter or a value declaration) you have to prefix it with a sigil, either an apostrophe or a hash mark:

```
let f1 't (x: [n]t) = x -- 't' bound explicitly here, 'n' must be in scope.
let f2 (x: [n]'t) = x -- 't' bound implicitly here, 'n' must be in scope.
let f3 't (x: [#n]t) = x -- 't' bound here, 'n' bound implicitly here.
let f4 (x: [#n]'t) = x -- 't' bound implicitly here, 'n' bound implicitly here.
let f5 #n (x: [n]'t) = x -- 't' bound implicitly here, 'n' bound explicitly here.
let f6 #n (x: [n]t) = x -- 't' must be in scope, 'n' bound explicitly here.
let f7 #n 't (x: [n]t) = x -- 't' bound explicitly here, 'n' bound explicitly here.
let f8 (x: [n]t) = x -- 't' must be in scope, 'n' must be in scope.
```

It's not quite as concise as what we currently have, but it is more precise.  It does allow us to express the same thing in multiple ways, though:

```
let matmult #n #m #p (x: [n][m]i32) (y: [m][p]i32): [n][p]i32 = ...
```

or

```
let matmult (x: [#n][#m]i32) (y: [#m][#p]i32): [#n][#p]i32 = ...
```

It also allows us to express something we can't right now, which is introducing *new* names in the return type of a function.  This is useful for expression e.g. the property that a function always returns a square array (but where we don't know anything else about the size:

```
let returns_square (p: i32): [#n][#n]i32 = ...
```

Or equivalently:

```
let returns_square #n (p: i32): [n][n]i32 = ...
```

Any of these changes will break compatibility with existing Futhark code, but that's not exactly a new occurrence.  I'd prefer to get all such breaks over with before the first release, so we have to make sure we are making the right decision.  I'll probably confer with @melsman before I decide on anything.
