### ISSUE TITLE
Refractor type checkers

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#33]
There are two type checkers, `src/Futhark/TypeCheck.hs` for the internal language and `src/Futhark/Representation/External/TypeChecker.hs` for the external language. 

Why not put the internal under `src/Futhark/Representation/` and the external under `src/Language/Futhark/`, so it matches the file structure of everything else (ie. the AST)

**Comment by Athas** [comment]
My original idea was to eventually factor `Language.Futhark` into its own separate library, which would be suitable if all you want is to generate Futhark code, without pulling in a full compiler.
