### ISSUE TITLE
Warning: Device limits tile size to 22 (setting was 32)

### ISSUE THREAD

**Issue by wvdschel** [HIPERFIT/futhark#335]
Everytime I run an OpenCL-compiled version of a Futhark program, I get the following message:
```
Warning: Device limits tile size to 22 (setting was 32)
```

I'm not sure if this is a problem or can safely be ignored. What does this mean?
I see this on three different computers running Linux. I see it using the Beignet driver for Intel, but I'm fairly confident I saw the same message on the proprietary Nvidia driver (though I'm not 100% on that).

**Comment by Athas** [comment]
During initialisation, the Futhark-generated code sets various constants that control parameters of execution.  These constants have compile-time defaults, but the defaults may exceed the capacity of the device found at runtime.  In this case, the constant is the "tile size" used for two-dimensional block tiling.  The default is 32, which works fine if the device support OpenCL workgroups with 32*32=1024 threads, but e.g. Intel GPUs only support groups of at most 512 threads.  Thus, after quering for limitations, the code recomputes a new tile size as the square root of the maximum group size; 22 in your case.  This is a bit of a weird number, and probably it ought to be a power of two, but it works fine.

I'd be surprised if you saw this warning on an NVIDIA GPU, although there's in principle nothing that prevents NVIDIA from creating a device or driver with a different group size restriction than 1024.

Perhaps a warning need not be issued for sizes that are still set to their compile-time default.  But this whole size business needs a rethought anyway - they are basically tuning parameters that cannot be optimally determined without knowing what hardware we are running on.

**Comment by wvdschel** [comment]
I'll verify on the Nvidia when I get home. I might have been running on the Intel HD by accident, I'm sure it's just a false memory.
