### ISSUE TITLE
Sharing work with CUDA-to-CL?

### ISSUE THREAD

**Issue by fenollp** [HIPERFIT/futhark#357]
I recently stumbled upon this amazing project: https://github.com/hughperkins/coriander
You guys may have some things to discuss :)

**Comment by Athas** [comment]
I definitely applaud efforts to create more interoperability between different GPU vendors!  However, it's not really relevant to Futhark.  We already generate OpenCL, and the process needed to turn Futhark code into OpenCL is radically different than what is needed for turning CUDA into OpenCL.

**Comment by fenollp** [comment]
I thought that since it seems he's writing LLVM backends that could be usefull for better opencl code generation. Also it might help if you guys want to target cuda :)
But yeah i opened this just to bring it up. Can stay closed. Thanks!
