### ISSUE TITLE
futhark-test opencl issue

### ISSUE THREAD

**Issue by LaurentPlagne** [HIPERFIT/futhark#360]
Hi,
I have installed futhark on my system: (stack setup-build-install)
ubuntu 17.04 GHC 8.0.2 GCC 6.3 I6700K/Nvidia GTX670
Futhark 0.1
git: 0e05b7b (Mon Jun 26 16:11:17 2017 +0200)
(C) HIPERFIT research centre
Department of Computer Science, University of Copenhagen (DIKU)

All the tests are OK. (futhark-test .)
For example 
`futhark-test linear_solve.fut`

`'0 failed, 1 passed. `

But when I try 
`futhark-test --compiler=futhark-opencl linear_solve.fut`

I obtain:
`Entry point: main; dataset: #0 ("[[1.0f32, 2.0f32, 1.0f32], [2.0f32, 1.0f32, 1.0f32..."):`

`Running compiled program:`

`Running ./linear_solve.bin -e main:`

`validating test result:`

`Program failed with error code 1 and stderr:`

` ./linear_solve.bin: Syntax error when reading [][]f32.`

`1 failed, 0 passed.`

I guess that there is something wrong with my opencl installation but my tests with pyopencl look OK...
What do I miss ?

Laurent

**Comment by Athas** [comment]
I assume it's [this](https://github.com/HIPERFIT/futhark/blob/master/examples/linear_solve.fut) `linear_solve.fut` program?

What happens if you manually compile `linear_solve.fut` with `futhark-opencl` and run

```
$ echo '[[1.0f32]] [1.0f32]' | futharki examples/linear_solve.fut
```

That "syntax error" message really just means "something/anything went wrong when reading the input".  *However*, at that point there is nothing OpenCL-related going on, and the exact same parser code is used by `futhark-c` and `futhark-opencl`, so this is pretty strange.

**Comment by LaurentPlagne** [comment]
> I assume it's this linear_solve.fut  program? 

 Yes !


`echo '[[1.0f32]] [1.0f32]' | futharki ./linear_solve.fut`
`[1.0f32]`
But
`futhark-opencl linear_solve.fut`
`echo '[[1.0f32]] [1.0f32]' | ./linear_solve`
`./linear_solve: Syntax error when reading [][]f32.`
While
`futhark-c linear_solve.fut`
`echo '[[1.0f32]] [1.0f32]' | futharki ./linear_solve.fut`
`[1.0f32]`

Strange...

**Comment by Athas** [comment]
That is incredibly strange.  The only explanation I can think of offhand is that OpenCL initialisation somehow corrupts memory elsewhere, leading to IO errors.  What happens if you try to run a program with OpenCL that has no input?  E.g. try this:

```
let main() = iota 10
```

**Comment by LaurentPlagne** [comment]
It works...
`futhark-c  toto.fut`
`./toto`
`[0i32, 1i32, 2i32, 3i32, 4i32, 5i32, 6i32, 7i32, 8i32, 9i32]`
`futhark-opencl  toto.fut`
`./toto`
`[0i32, 1i32, 2i32, 3i32, 4i32, 5i32, 6i32, 7i32, 8i32, 9i32]`

**Comment by Athas** [comment]
I just made a few commits to preserve slightly more error information in the value reader.  Fetch a new version of Futhark and then try running the following programs with both `futhark-c` and `futhark-opencl`.  When running the OpenCL versions, pass `-s` to get a little more debug information.  I'm mostly curious about whether it picks up the correct platform and device:

```
let main(x: i32) = x
```

```
let main(x: []i32) = x
```

Also, if you have happen to have a working PyOpenCL setup, you could try using `futhark-pyopencl`.  The generated program should at least fail with a different error.

**Comment by LaurentPlagne** [comment]
Hi Troels,  I feel more and more embarrassed to waste your time with my probable corrupted linux configuration...
After a fresh install:
----------
futhark-c toto.fut
2i32
-----------
futhark-opencl toto.fut
echo 2 | ./toto -s
Using platform: Intel(R) OpenCL
Using device: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
./toto: Error when reading input of type i32 (errno: Success).
-----------
futhark-pyopencl toto.fut
lolo@lolo-Z170XP-SLI:~/Public/futhark/examples$ echo 2 | ./toto 
/usr/lib/python2.7/dist-packages/pyopencl/cffi_cl.py:1466: CompilerWarning: Built kernel retrieved from cache. Original from-source build had warnings:
Build on <pyopencl.Device 'Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz' on 'Intel(R) OpenCL' at 0x560f030f0978> succeeded, but said:

Compilation started
Compilation done
Linking started
Linking done
Device build started
Device build done
Kernel <dummy_kernel> was successfully vectorized (8)
Done.
  warn(text, CompilerWarning)
/usr/lib/python2.7/dist-packages/pyopencl/cffi_cl.py:1466: CompilerWarning: From-binary build succeeded, but resulted in non-empty logs:
Build on <pyopencl.Device 'Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz' on 'Intel(R) OpenCL' at 0x560f030f0978> succeeded, but said:

Device build started
Device build done
Reload Program Binary Object.
  warn(text, CompilerWarning)
Traceback (most recent call last):
  File "./toto", line 1724, in <module>
    entry_point_fun()
  File "./toto", line 1696, in entry_main
    x_243_ext = read_i32(input_stream)
  File "./toto", line 1215, in read_i32
    return read_general(f, FUTHARK_INT32)
  File "./toto", line 1203, in read_general
    if read_is_binary(f):
  File "./toto", line 1074, in read_is_binary
    skip_spaces(f)
  File "./toto", line 781, in skip_spaces
    c = get_char(f)
  File "./toto", line 758, in get_char
    return f.read(1)
IOError: [Errno 9] Bad file descriptor

**Comment by Athas** [comment]
Don't be embarrassed!  I'm just happy it seems like this isn't Futhark's fault after all. :-)

Based on the debugging information, it looks like Futhark is using some Intel OpenCL backend by default (unless told otherwise, Futhark just picks the first platform it finds).  This backend then proceeds to corrupt the standard input file descriptor, probably by closing it.  I'm not terribly surprised - on our big machines, the Intel OpenCL backend invariably segfaults with an error in some vectorizer.

The solution is to explicitly tell Futhark which OpenCL backend (or "platform", in OpenCL jargon) to use.  To this with the `-p` option to the executables.  For example, `./toto -p NVIDIA` should tell it to use the NVIDIA platform instead of the Intel platform.

**Comment by LaurentPlagne** [comment]
Great ! Thank you for your help ! I will let you know about my Futhark's experiments ;)

**Comment by Athas** [comment]
Have fun!  Getting the GPU crud working is definitely one of the major obstacles to clear.  Maybe we should document common problems.

If you still want to use `futhark-test`/`futhark-bench`, you can use ``pass-option=-pNVIDIA`` to pass along ``-pNVIDIA`` to the generated executables.
