### ISSUE TITLE
Bug in the in-place lowering optimisation

### ISSUE THREAD

**Issue by nqpz** [HIPERFIT/futhark#361]
I can see that the optimisation is back.  However, when I run `futhark --cpu` on this (somewhat contrived) program
```
let main (xs: *[#n][#n]i32, ys0: [#n]i32, i: i32): ([n][n]i32, i32) =
  let ys = map (+ 1) ys0
  let zs = map (+ 1) xs[i]
  let xs[i] = ys
  in (xs, zs[i])
```
I get the error message
```
Type error after pass 'In-place lowering':
In function main
Type error:
Variable xs_421 referenced after being consumed.
```
If I disable in-place lowering, I don't get an error message.

**Comment by Athas** [comment]
That's right, this is one of the safety checks are documented to not be implemented.  Since we are getting rid of in-place lowering anyway, I have little motivation to improve it.

**Comment by nqpz** [comment]
Fair enough.
