### ISSUE TITLE
Extending array literal syntax to support ranges?

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#362]
Many programming languages support a concise notation for intervals of integers.  For example, in Haskell:

```
[1..9] == [1,2,3,4,5,6,7,8,9]
```

They can also be descending:

```
[9,8..1] == [9,8,7,6,5,4,3,2,1]
```

Although you have to be explicit:

```
[9..1] == []
```

Also, you can have a stride other than unit:

```
[1,3..9] == [1,3,5,7,9]
```

This syntax has some value by itself, but it would be particularly useful in conjunction with #351 for expressing complicated iteration spaces.  E.g. instead of

```
for i in map (12-) (map (1+) (map (2*) (iota 6)))
```

one can write

```
for i in [11,9..1]
```

Of course, this could also be simulated using a suite of library functions.  One can imagine an application `from_downto_by 11 0 1` that simply computes the necessary `map`s and `iota`s.

Is a dedicated syntax useful?  If we decide that it is, *then* we need to decide on sticky issues like whether the bounds should be include (as in Haskell) or exclusive (as in `iota`, and our array slicing syntax, and what Dijkstra recommends in EWD831).

**Comment by Qata** [comment]
I think this dedicated syntax would be fantastic to have. Whether or not it's inclusive could be dealt with by using two operators (like Swift did). `...` for inclusive of the target element and `..<` for exclusive of the target element.

`0...5 == [1,2,3,4,5]`
`0..<5 == [1,2,3,4]`

**Comment by Athas** [comment]
That's not a bad notation.  It even seems to mesh well with descending ranges:

    5,4..1 == [5,4,3,2,1]
    5,4..>1 == [5,4,3,2]

**Comment by Qata** [comment]
Oh wow I hadn't even considered that. Nice 👍

**Comment by Athas** [comment]
The only sad thing is that array slicing has a different syntax for approximately the same thing, i.e. `a[1:5:2]` vs `[1,3...5]`.  Let's see if we can unify them.  We can't immediately use the new range syntax for array slicing as well, because comma has a special significance there, for distinguishing dimensions.  That could change too, of course: instead of `a[i,j]`, we could require `a[i][j]`.  Wouldn't be the end of the world.

Another problem of unification is that array slicing supports some short-hands that are possible because the array bounds are always known.  For example `a[::-1]` is used to reverse an array (and `a[::]==a`).  How would that look now?  Assuming the size of `a` is `n`, it can be written explicitly as `a[n-1,n-2...0]`, but that is sort of gnarly.  We can always come up with more syntax: `a[>...0]`, or even more implicitly, `a[>...]`.  This is beginning to look a little magical, but I guess `a[::-1]` isn't terribly intuitive either unless you know Python.

**Comment by RasmusWL** [comment]
I think it would be nice adding this :)

Also, for *writing* programs I think `[1,3...5]` is much preferable, but for working in the compiler I think `[1:5:2]` would make more sense. I see no reason that we couldn't use `[1,3...5]` in the source language.

**Comment by Athas** [comment]
The compiler internally uses a slightly different notation for array slices: `a[start:+num_steps*stride]`.  It is easier for the compiler to deal with because the length of the slice is clear (it's `num_steps`).

For ranges, the internaliser will just turn them into `map`-`iota` compositions.  No reason to extend the core language to get this sugar.

**Comment by Athas** [comment]
The `a[i,j]` syntax is only used in three tests and and one benchmark (Game of Life), so I'm quite comfortable with removing it and requiring `a[i][j]` instead.  It is anyway a closer fit for the recursive structure of multidimensional arrays that Futhark emphasises.

**Comment by Athas** [comment]
Oh, and those tests are all derived from @melsman's `sobol.fut` file.  Looks like he's the only one (apart from me) who ever used this syntax.

**Comment by nqpz** [comment]
I also use the `a[i, j]` syntax, but to be honest I often find myself writing `a[i][j]` at first (since that is how it is done in many mainstream languages), so from a boring ease of use perspective I would not mind the change.

**Comment by oleks** [comment]
`a[i,j]` saves me a keystroke.

**Comment by Qata** [comment]
Amount of keystrokes aside, I'm in favour of the `a[i][j]` syntax. It's familiar to any programmer that has used a C-like language.

**Comment by coancea** [comment]
I am with Oleks here: a[i,j] looks tidier to me — not only extra keystroke but also they look big and ugly in comparison with the comma.

However, the majority rules.

Cosmin

**Comment by Athas** [comment]
Maybe we don't need to change the syntax - we just need to come up with a unified syntax for ranges and slices that does not involve commas.  Instead of `1,3..15`, maybe `1..3..15`?

**Comment by Athas** [comment]
Not using commas is necessary if we want to permit ranges without surrounding brackets, due to an ambiguity with tuples: is `(1,3...15)` a range encloses in parentheses, or a pair of an integer and a range?  There is no such ambiguity with `(1..3...15)`.  For that matter, the ambiguity occurs with brackets, too: is `[1,3..15]` a literal array containing an integer and a range, or a single range?  Only the latter would be type-correct in this case, but consider a symbolic case like `[x,y..z]` instead.  Also, it can be hard to read: how many elements are in `[1,3...15,3,5...17]`?  I think `[1..3...15,3..5...17]` is easier to read.  Thus, using double-dot is better than comma for indicating a stride.  This means we can stick with the current array index syntax.

One question remains: should brackets be required around ranges?  I.e. is `1...5` valid or should one write `[1...5]`?  Haskell does the latter, while Swift does the former.  I don't think there are any issues with ambiguity here, but there are many cases where `1..5` would require parenthesis.  For example, `f 1..5` will be parsed as `(f 1)..5`, which is likely not what is intended.  `f [1..5]` feels more predictable, and if we really want to apply a function to the starting point, `[f 1..5]` looks OK to me.
