### ISSUE TITLE
Cleaning up file inclusion

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#365]
There are still some edge cases on file inclusion that don't work well, and they are preventing Henrik's work on doc generation from being completely smooth.

The basic problem is that the same file can be referred to by multiple names, because we support relative paths in ``include``.  Consider a directory tree of Futhark source files:

```
a.fut
d/b.fut
d/c.fut
```

Inside a.fut, we can use ``import "d/b"`` or ``import "/d/b"`` to refer to the file d/b.fut.  Inside d/c.fut, we can use ``import "b"`` or ``import "/d/b"``.  Actually, by using ``..`` and ``.`` in paths, there is an infinite amount of distinct names for every file.  There is a notion of a "root" that is used to resolve absolute paths.  For the compiler, this the directory containing the given source file.  For a tool like ``futhark-doc``, it's less clear, but that's not the main problem.

The question is: is it a problem that we can refer to the same file by multiple names?  It is not in principle hard to do a bit of normalisation inside the compiler so that it, at least, does not get confused.

The motivation behind supporting relative import paths was to permit the writing of Futhark libraries that can be integrated simply by copying their directory hierarchy.  Since Futhark code will, in practice, probably not be the main part of any application, I tried to design the language such that it will not *require* any language-specific build or package management tool (although such a tool could still be made one day).  Maybe we can achieve this goal without supporting relative import paths.  However, does this mean ``import "b"`` would be banned, and require us to write ``import "/b"`` instead?  That seems like a useless bit of pedantry.

**Comment by nqpz** [comment]
I like having both the option of
  1. using `import` as in a typical modern programing language where the path is relative to the root file;
  2. and using `import` in an ad-hoc, make-this-work-now, development kind of way where you just give a path to the file.

If one of the approaches has to go, I could live with losing option 2.  If it can stay, I could live with losing the ability to refer to ".." paths.  But unless it's a big problem, I would like to keep them all.

**Comment by Athas** [comment]
I think it is realistic to support both.  It will allow programmers to make royal messes with `..` and the like, but that's not really our problem.
