### ISSUE TITLE
Mistake in Language Overview

### ISSUE THREAD

**Issue by medakk** [HIPERFIT/futhark#370]
I was going through [this page](https://futhark.readthedocs.io/en/latest/language-overview.html#sequential-loops) as a starting point to learning futhark, and one of the examples did not compile:
```
let fib(n: i32): i32 =
  let (x, y) = loop (x, y) = (1,1) for i < n do (y, x+y)
  in x
```
```
$ futhark-c test_loop.fut 
Parse error at ./test_loop.fut:2:25-2:25
If you find this error message confusing, uninformative, or wrong, please open an issue at https://github.com/HIPERFIT/futhark/issues.
```

It compiles when I wrap the `(x, y) = (1,1)` in parantheses:
```
let fib(n: i32): i32 =
    let (x, y) = loop ((x, y) = (1,1)) for i < n do (y, x+y)
    in x
```

EDIT:
```
$ futhark --version
Futhark 0.1
git: 839a091 (Sat Jul 1 23:21:05 2017 +0200)
(C) HIPERFIT research centre
Department of Computer Science, University of Copenhagen (DIKU)
```

**Comment by Athas** [comment]
The parentheses were grammatically redundant, so they were removed in #368 a few days ago.  Just re-pull the Futhark compiler (or get the newest nightly build) and the example should work.

**Comment by medakk** [comment]
OK. Thanks!

--
Karthik Karanth
