### ISSUE TITLE
A silly lexer issue

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#373]
Turns out that the following is not valid Futhark:

    [1...0]

The issue is that it is being tokenised as:

```
[
1.
..
0
]
```

The problem here is that Futhark's lexical syntax accepts `1.` as a decimal literal.  This is a fairly recent addition that I copied from OCaml without really thinking it through.  Haskell does not permit this, presumably so range will work.

A workaround is to just add spaces - `[1 ... 10 ]` - but this is an error that will occur the first time anyone tries out ranges.

How should this be fixed?  The lexer generator we are using does not permit lookahead, so we cannot say that `1.` is a token only if not followed by another dot.  (Although I think I could hack it to get something equivalent.)  We could also go back to requiring at least one digit after a decimal point.  In the future, when we have type inference, we will hopefully get polymorphic constants, and this will be less necessary.

**Comment by Qata** [comment]
I'd be in favour of requiring a digit after a decimal point until type inference is a thing. It's not that big of a sacrifice.
