### ISSUE TITLE
Add coding style guidelines

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#42]
Just to have some consistency.  It would be nice if it also contained some Emacs configuration to make following the style more convenient.

**Comment by RasmusWL** [comment]
Would be great... I think I'm currently breaking it :)

**Comment by Munksgaard** [comment]
Was there ever created an Emacs configuration that enforce (a subset of) the coding style guidelines?

**Comment by athas** [comment]
Not that I know of.  Is it even possible?

When the style guide was written, I don't think there were any good Haskell code formatters.  There is [brittany](https://hackage.haskell.org/package/brittany) now and I would certainly support mechanising the style guide (even changing it to accomodate what brittany or some other tool can handle).

**Comment by Munksgaard** [comment]
I'm not that familiar with Haskell formatters and style checkers, but it should be possible to create an emacs configuration that only indents two spaces, highlights (and/or deletes) trailing whitespace and breaks lines over 80 characters. 

My main reason for asking is that my haskell indentation module (haskell-indent) uses 4 characters to indent by default, and I've been too lazy to figure out how to change it.

**Comment by Munksgaard** [comment]
I don't know much about brittany, but if it's anything like rustfmt or gofmt I'm all for it.

**Comment by Munksgaard** [comment]
For the record, this is what Brittany does to src/Futhark/Representation/ExplicitMemory/IndexFunction.hs: https://github.com/Munksgaard/futhark/commit/4728886e16f531802b447a1bb1d6ecbf98f3d20b?diff=split using the standard options on https://hexagoxel.de/brittany/ and version 0.12.1.1. It's opinionated about certain things, like imports, but apart from that I think the changes are not unreasonable.

**Comment by athas** [comment]
I'm not a big fan of everything it does, but I guess I could live with it.  Do people normally use Brittany without options?

**Comment by Munksgaard** [comment]
An alternative is [ormolu](https://github.com/tweag/ormolu). It's a bit more opinionated than brittany as far as I can tell, and doesn't allow for a lot of customization. However, it seems like it can correctly parse all of the code in this project, while still making it compile. I tried a test-run here, so you can see what it's like: https://github.com/Munksgaard/futhark/commit/0ace4c2782a7fba4bb126f40f9382a400148049c. There's some [weird stuff](https://github.com/Munksgaard/futhark/commit/0ace4c2782a7fba4bb126f40f9382a400148049c#diff-40766bfb052369ad0a2398477a191d55R397-R405) going on here and there, but I don't think it's terrible.

**Comment by Munksgaard** [comment]
More info here: https://www.tweag.io/posts/2019-05-27-ormolu.html

**Comment by athas** [comment]
That looks pretty good.  The only thing I find immediately objectionable is adding a space between a constructor and an empty record (`Foo{}`), but as I've said before, I am willing to make sacrifices in order to get automation.

**Comment by kfl** [comment]
Might I also suggest taking *diff friendliness* into account. See [Evolving Import Style For Diff Friendliness](https://www.parsonsmatt.org/2020/03/17/gradual_import_style_improvements.html) for an example of how to set up [`stylish-haskell`](https://hackage.haskell.org/package/stylish-haskell). (Incidently that style matches my preferred style). 

Alas, I think `stylish-haskell` is only for `imports`.

**Comment by kfl** [comment]
@Munksgaard if you are interested here is my Haskell setup for emacs:

```el
(setq-default indent-tabs-mode nil)
(setq-default tab-width 2)

(use-package haskell-mode
  :ensure t
  :init
  (add-hook 'haskell-mode-hook 'turn-on-haskell-doc-mode)
  (add-hook 'haskell-mode-hook 'turn-on-haskell-indentation)
  (add-hook 'haskell-mode-hook 'haskell-indent-mode)
  (setq-default haskell-process-show-debug-tips nil))

(use-package intero
  :ensure t
  :init
  (add-hook 'haskell-mode-hook 'intero-mode))
```

I think `(setq-default tab-width 2)` is the important part for you. (And yes, I should switch to `dante` over `intero`.)

**Comment by athas** [comment]
I used stylish-haskell for a little while once, but I found its impact relatively limited.  I don't think it's worth mandating its use.  I would rather just use a proper code formatter.  `ormulu` is my favourite so far.

**Comment by Munksgaard** [comment]
> @Munksgaard if you are interested here is my Haskell setup for emacs:

Thank you, that's very helpful!

**Comment by Munksgaard** [comment]
> Might I also suggest taking _diff friendliness_ into account. See [Evolving Import Style For Diff Friendliness](https://www.parsonsmatt.org/2020/03/17/gradual_import_style_improvements.html) for an example of how to set up [`stylish-haskell`](https://hackage.haskell.org/package/stylish-haskell). (Incidently that style matches my preferred style).

I agree. For the record, I think ormolu's style mostly matches the style proposed in the post you linked.
