### ISSUE TITLE
Which optimisations are permissible?

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#47]
At the HIPERFIT reading group meeting, we discussed whether it is permissible for the optimiser to convert non-terminating programs into terminating ones.  I am still not convinced one way or the other (but currently the Futhark compiler will indeed do that).

Basically, the question is whether the two propositions "the unoptimised program computes V" and "the optimised program computes V" are connected by implication or bi-implication.

If we want this to be a bi-implication, we may hinder ourselves quite a bit, for example by not permitting removal of a division expression (even as dead code) unless we can statically prove that the divisor is non-zero.

**Comment by henglein** [comment]
That's bit of red herring question.

An 'optimiser' changes program semantics anyway -- its very purpose is to
change a program (with a semantics and cost model) into another one subject
to keeping something invariant.   The most important thing, I believe, is
being able to say something precise as to what an optimizer keeps invariant
and what it may change: e.g

"It rearranges data structures and computations resulting in changes (with
fingers crossed and a couple of Hail Marys: improvements) of resource
consumption, but it'll always have the same (infinitary) external behavior."

Or

"It does the above, plus furthermore doesn't increase space consumption
(absolutely or asymptotically) -- no space leaks."

Or

"It preserves (finitely observable) external behavior, and futhermore, it
never makes run time performance worse; it may improve run time
performance, including the possibility of returning something where the
original runs on for ever (in both cases according to the program
semantics, not some implementation machine)."

The latter says the optimizer may return a program that terminates more
often than the original -- this arguably falls into the category of
"improving run time".

Invariants preserved include those maintaining certain performance
relations between *pairs* of input programs; e.g. "the optimizer always
yields a program that is at least as fast for source program e[c/x] as for
source program let x = c in e[x]".

Fritz

**Comment by Athas** [comment]
Determining how the optimiser may change edge cases (or modifying the language such that edge cases become impossible, e.g. by totality) is exactly the issue here.

I realised that the issue will in fact crop up with something even simpler than dead code elimination - in the expression `a[-1] + diverge()`, it is based on evaluation order whether the program terminates with a range error or diverges, and Futhark does not specify evaluation order.

My conclusion is to not worry much about this for now, since this seems like a profound research question, and it is mostly orthogonal to what we try to do with Futhark.

**Comment by Athas** [comment]
Different kinds of nontermination cannot be distinguished.  An invalid/nonterminating program may become terminating through optimisation.  There is no reason to spend more cycles on this.
