### ISSUE TITLE
Utility function for splitting a redomap into seperate reduce and map

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#52]
Would just be nice to have. For example `redomap` does not make much sense for flattening.

---

Would also be nice to have better documentation for the internal `redomap`.

**Comment by Athas** [comment]
For documentation, you'll need to talk to Cosmin.

**Comment by RasmusWL** [comment]
Fixed in ac75e09737ab3b5b605a1730dc6f5e40392c3529
