### ISSUE TITLE
freeInExp is broken

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#54]
`freeInExp` from `Futhark/Representation/AST/Attributes/Names.hs` does no longer produce correct results. Running it on the following expression

```
map(fn {[int,size_12]} ([int,size_12] x_55 (()), [int,size_26] x_56 (())) =>
      let {[int,size_12] ys_zip_res_63} = <zip_assert_62>reshape((size_12),
                                                                 x_56) in
      let {[int,size_12] res_67} =
        map(fn {int} (int x_64 (()), int y_65 (())) =>
              let {int res_66} = x_64 + y_65 in
              {res_66},
            x_55, ys_zip_res_63) in
      {res_67},
    A_27, B_zip_res_37)
```

Gives the these free variables
`[size_12, x_55, size_26, x_56, zip_assert_62, x_64, y_65, A_27, B_zip_res_37]`

My understanding is that this should only be:
`[size_12, size_26, zip_assert_62, A_27, B_zip_res_37]`

**Comment by concieggs** [comment]
Rasmus Wriedt Larsen <notifications@github.com> writes:

> `freeInExp` from `Futhark/Representation/AST/Attributes/Names.hs` does no longer produce correct results. Running it on the following expression
>
> ```
> map(fn {[int,size_12]} ([int,size_12] x_55 (()), [int,size_26] x_56 (())) =>
>       let {[int,size_12] ys_zip_res_63} = <zip_assert_62>reshape((size_12),
>                                                                  x_56) in
>       let {[int,size_12] res_67} =
>         map(fn {int} (int x_64 (()), int y_65 (())) =>
>               let {int res_66} = x_64 + y_65 in
>               {res_66},
>             x_55, ys_zip_res_63) in
>       {res_67},
>     A_27, B_zip_res_37)
> ```
>
> Gives the these free variables
> `[size_12, x_55, size_26, x_56, zip_assert_62, x_64, y_65, A_27, B_zip_res_37]`
>
> My understanding is that this should only be:
> `[size_12, size_26, zip_assert_62, A_27, B_zip_res_37]`

You are right.  I will fix this.

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
I see that concieggs is already on this one.

This is a horribly embarassing bug that would be caught right quick if
we had anything resembling a proper unit testing suite.  It cannot go on
like this.

-- 
\  Troels
/\ Henriksen
