### ISSUE TITLE
Replace `real` with `single` and `double`

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#56]
The `real` type does not belong in a low-level language.  I will add a compiler flag that will control whether `real` is translated to `single` or `double` at parse-time (or maybe internalisation-time).

Of course, in the newest floating point spec, `single` and `double` are no longer official names - these would be `binary32` and `binary64` respectively.  Maybe `float32` and `float64` would be better names?  Or perhaps that is too unusual.

**Comment by Athas** [comment]
I will use `float32` and `float64` instead.  This meshes well with the other types we will add in the future.

**Comment by sshine** [comment]
`float32` and `float64` sound good.

**Comment by Athas** [comment]
Got this implemented.
