### ISSUE TITLE
filter on array of tuple results in "different" size arrays

### ISSUE THREAD

**Issue by RasmusWL** [HIPERFIT/futhark#62]
This following code (`futhark/data/tests/soacs/filter3.fut`)

```
fun [{bool,int}] main([{int,bool}] xs) =
  let tmp = filter(fn bool ({int,bool} x) =>
                     let {i,b} = x in b
                  , xs) in
  map(fn {bool,int} ({int,bool} x) =>
        let {i,b} = x in {b,i}
     , tmp)
```

which is internalised to something like

```
  let {int filter_size_42, [int,size_0] filter_perm_43} = partition(1,filter_partition_flags_10,xs_1) in
  let {[int,filter_size_42] res_44} = split((filter_size_42), filter_perm_43) in

  let {int filter_size_45, [bool,size_0] filter_perm_46} = partition(1,filter_partition_flags_10,xs_2) in
  let {[bool,filter_size_45] res_47} = split((filter_size_45),filter_perm_46) in

  map(..., res_44, res_47)
```

Results in the following error
`SOAC argument res_47 has outer size filter_size_45, but argument res_44 has outer size filter_size_42`

**Comment by Athas** [comment]
I am fixing this.  It will be done by making `partition` able to partition multiple arrays at once.  This is more efficient anyway.  We may need an optimisation to turn multiple `partition`s with the same flag array into just one `partition`.
