### ISSUE TITLE
Rework reshape()

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#72]
We use `reshape` in two different ways: one is as the programmer-level construct for actually reshaping arrays (`reshape` in the external language), and one for as a pseudo-typecast for arrays to make function return and argument types match up, but where the actual dimensions don't change in the numerical sense.  Right now, the compiler assumes nothing about `reshape`, because it does not know what it comes from, but this means we have thrown away information.  Consider:

```
-- dims(a) = [m0,n0]
let b = transpose(a) -- dims(b) = [n0, m0]
let c = reshape((n1,m1), b) -- dims(c) = [n1, m1]     
```

If the `reshape` is a "real" reshape, it is invalid to swap the `transpose` and `reshape` operations.  If, however, `n` and `m` are equal to `n0` and `m1` respectively, we can swap:

```
-- dims(a) = [m0,n0]
let b = reshape((m1, n1), a) -- dims(b) = [m0, n0]
let c = transpose(b) -- dims(c) = [n1, m1]     
```

This is sometimes useful, particularly when it comes to simplifying index functions.

One solution to this problem is to introduce an entirely new `shapecast` construct, which is like `reshape`, but with the invariant that the dimensions do not actually change.  I am a little skeptical about this approach, because we may sometimes want to "fuse" two `reshape`s into a single `reshape`.  If the involved expressions are a `shapecast` and a `reshape`, we would be forced to fuse to a `reshape`, which loses information.

My suggestion is thus to extend `reshape` in such a way that for every dimension given, we also give a flag specifying whether there is an actual change in dimension, or just a change of name.  This flag is given by a `~` preceding the new dimension.  For example:

```
reshape((~n), a) -- result has shape [n], but n==size(0,a)
reshape((~n, m), b) -- result has shape [n,m], where n==size(0,b).  m can be anything.  As a special case, if rank(b)==2, then we must also by necessity have m==size(1,b)
```

This would certainly simplify index functions, and possibly enable other optimisations that are currently hindered by the large amount of `reshape`s present due to our type rules.

**Comment by Athas** [comment]
I have been working on this and it is pretty much working perfectly.  Even with delayed transpose/rearrange operations, we get very nice affine index functions in both OptionPricing and CalibVolDiff.

**Comment by RasmusWL** [comment]
This is quite possibly the best thing you have done for Futhark developers in a long time!

**Comment by Athas** [comment]
Then come back and finish flattening!
