### ISSUE TITLE
Parallel scans

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#83]
We sequentialise `scan` at the moment.  Clearly this won't do in the long run.  We need scans for parallelising all three levels of the `CalibVolDiff` benchmark.

**Comment by Athas** [comment]
Working on this for now.  Trying to figure out how to implement an inclusive variant of Blelloch's scan algorithm.

**Comment by Athas** [comment]
I cannot think of a way to do this that does not involve recursion.  How annoying.

**Comment by concieggs** [comment]
Okay, this is the way it's gonna be (unless Cosmin tells me that it's stupid):

  0) The input array has N elements.

  1) Determine a workgroup size K and a number of workgroups W.  These
     values are not related to N at all, but are based on the GPU (and
     possibly the kernel itself).  This is the same thing we do for
     reductions.  For now, let us assume that W is less than the maximum
     workgroup size.

  2) Each workgroup performs an inclusive scan on `N / (K * W)` elements,
     producing `N / K * W` elements as output.  We now have an array
     where each `K*W`-size chunk has been scanned.

  3) For each chunk, take the *last* element.  This results in a size-W
     array.  Compute the *exclusive* scan of this array.  This can be
     done using a single workgroup if W is less than the maximum
     workgroup size.

  4) We now have a size-W array of "offsets".  Call this array
     `OFFSETS`.  For any chunk `i`, use the scan operator to combine
     `OFFSETS[i]` with all elements in the chunk.  This is just a map.

  5) Enjoy your new inclusively scanned array.

Possible issues:

  * In step (2), each K-thread workgroup must scan `N / (K * W)`
    elements.  This means every thread will have to process several
    elements - most of the optimised GPU scan implementations I have
    seen do not do this, which makes me uneasy.  Still, this should only
    happen for large inputs, in which case we should have enough work to
    saturate the hardware.  We must be careful to prevent branch
    divergence.

  * Step (2) calls for an inclusive scan, but Blelloch's algorithm is an
    exclusive scan.

  * I suppose that we can let W be greater than the maximum workgroup
    size by sequentialising in step (3).  The most important thing is
    that step (3) can be done within a single workgroup (or in
    principle, a statically known number), as we otherwise end up with
    recursion.

  * Step (3) can get away with doing an inclusive scan if we index with
    `i-1` (and special-case the first chunk) in step (4).

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
Okay, this is the way it's gonna be (unless Cosmin tells me that it's stupid):

  0) The input array has N elements.

  1) Determine a workgroup size K and a number of workgroups W.  These
     values are not related to N at all, but are based on the GPU (and
     possibly the kernel itself).  This is the same thing we do for
     reductions.  For now, let us assume that W is less than the maximum
     workgroup size.

  2) Each workgroup performs an inclusive scan on `N / (K * W)` elements,
     producing `N / K * W` elements as output.  We now have an array
     where each `K*W`-size chunk has been scanned.

  3) For each chunk, take the *last* element.  This results in a size-W
     array.  Compute the *exclusive* scan of this array.  This can be
     done using a single workgroup if W is less than the maximum
     workgroup size.

  4) We now have a size-W array of "offsets".  Call this array
     `OFFSETS`.  For any chunk `i`, use the scan operator to combine
     `OFFSETS[i]` with all elements in the chunk.  This is just a map.

  5) Enjoy your new inclusively scanned array.

Possible issues:

  * In step (2), each K-thread workgroup must scan `N / (K * W)`
    elements.  This means every thread will have to process several
    elements - most of the optimised GPU scan implementations I have
    seen do not do this, which makes me uneasy.  Still, this should only
    happen for large inputs, in which case we should have enough work to
    saturate the hardware.  We must be careful to prevent branch
    divergence.

  * Step (2) calls for an inclusive scan, but Blelloch's algorithm is an
    exclusive scan.

  * I suppose that we can let W be greater than the maximum workgroup
    size by sequentialising in step (3).  The most important thing is
    that step (3) can be done within a single workgroup (or in
    principle, a statically known number), as we otherwise end up with
    recursion.

  * Step (3) can get away with doing an inclusive scan if we index with
    `i-1` (and special-case the first chunk) in step (4).

**Comment by RasmusWL** [comment]
Cool stuff. This would also mean that if *someone* where to implement a flattening transformation that assumes parallel scans are fast, it would probably work :smile:

**Comment by Athas** [comment]
Yes!  Although I think you will need segmented scans too.  Do you intend to finish your work on flattening?

**Comment by Athas** [comment]
First succesful parallel scan executed.  This program (tests/soacs/scan1.fut):

```
fun [int] main([int] a) = scan(+, 0, a)
```

With an input size of 10.

It is not... great.  We assume that entire blocks of the input will fit in shared memory.  But it will suffice, I hope.  Currently, multidimensional scans are not supported.

**Comment by Athas** [comment]
Now tested with an input size of 3000 - still works.  (After fixing it.)

**Comment by Athas** [comment]
Works well for scalars now.  Still a little uncoalesced access going on.
