### ISSUE TITLE
Better syntax for power operator

### ISSUE THREAD

**Issue by Athas** [HIPERFIT/futhark#88]
Whilst implementing #86 I once again had the misfortune to have to use the power operator.  `pow`, really?  This is perhaps the last remnant of dubious SML-inspired syntax left in Futhark, and we should get rid of it.

Note that `^` is not available, as it is used for xor as Dennis intended.

**Comment by RasmusWL** [comment]
How about `x ** y`? (as in Python and Haskell)

**Comment by concieggs** [comment]
Rasmus Wriedt Larsen <notifications@github.com> writes:

> How about `x ** y`? (as in Python and Haskell)

Yes!  Not bad at all.  Do you want to implement it?

-- 
\  Troels
/\ Henriksen

**Comment by Athas** [comment]
I am the guy wearing the concieggs suit.
